// Mutproben. Nur eine Person macht sie, die andere entscheidet, ob sie zählt.
//
// { id, ort: 'überall' | 'flug' | 'stadt' | 'abend', q }
//   überall  geht immer — Sitzplatz, Hotelzimmer, Café
//   flug     unterwegs: Flughafen, Flieger, Bahn, Taxi
//   stadt    draußen in Wien, bei Tageslicht unter Leuten
//   abend    Bar, Restaurant, später Abend

export const WAGNIS = [
  // ── Überall ─────────────────────────────────────────────────────────────
  { id: 'u01', ort: 'überall', q: 'Erzähle die Handlung deines Lieblingsfilms in 60 Sekunden — rückwärts.' },
  { id: 'u02', ort: 'überall', q: 'Sprich die nächsten fünf Minuten wie ein Nachrichtensprecher. Auch beim Bestellen.' },
  { id: 'u03', ort: 'überall', q: 'Zeichne mich, ohne einmal auf das Papier zu schauen. Das Ergebnis wird fotografiert.' },
  { id: 'u04', ort: 'überall', q: 'Sag mir drei Minuten lang ununterbrochen Dinge, die du an mir magst. Keine Pause, keine Wiederholung.' },
  { id: 'u05', ort: 'überall', q: 'Setz mein dümmstes Foto als mein Kontaktbild in deinem Handy — für den Rest des Urlaubs.' },
  { id: 'u06', ort: 'überall', q: 'Sprich die nächste Viertelstunde ausschließlich in Fragen.' },
  { id: 'u07', ort: 'überall', q: 'Lass mich die nächsten drei Songs aussuchen. Du hörst sie ganz, ohne Kommentar.' },
  { id: 'u08', ort: 'überall', q: 'Lies mir die letzte Nachricht vor, die du deiner besten Freundin oder deinem besten Freund geschickt hast.' },
  { id: 'u09', ort: 'überall', q: 'Erfinde aus dem Stand ein Gedicht über mich. Vier Zeilen, es muss sich reimen.' },
  { id: 'u10', ort: 'überall', q: 'Mach 20 Kniebeugen. Jetzt. Wo du gerade bist.' },
  { id: 'u11', ort: 'überall', q: 'Imitiere mich, bis ich lachen muss. Du hast zwei Minuten.' },
  { id: 'u12', ort: 'überall', q: 'Schreib mir eine Nachricht, die du mir vor zehn Jahren geschickt hättest — und lies sie laut vor.' },
  { id: 'u13', ort: 'überall', q: 'Rede eine Minute lang nur in Reimen.' },
  { id: 'u14', ort: 'überall', q: 'Zeig mir das älteste Foto auf deinem Handy und erzähl die Geschichte dazu.' },
  { id: 'u15', ort: 'überall', q: 'Sing mir zwei Zeilen aus dem Lied, das bei unserer Hochzeit lief.' },
  { id: 'u16', ort: 'überall', q: 'Lass mich dein Handy 60 Sekunden lang halten. Ich darf eine App öffnen, du schaust zu.' },
  { id: 'u17', ort: 'überall', q: 'Halte eine ernsthafte 90-Sekunden-Rede über ein völlig belangloses Thema, das ich dir gebe.' },
  { id: 'u18', ort: 'überall', q: 'Erzähl mir eine Geschichte aus deinem Leben, die ich garantiert noch nicht kenne.' },
  { id: 'u19', ort: 'überall', q: 'Sprich bis zur nächsten Runde nur im Flüsterton.' },
  { id: 'u20', ort: 'überall', q: 'Beschreibe unseren letzten Streit aus meiner Sicht — fair und ohne Ironie.' },
  { id: 'u21', ort: 'überall', q: 'Massiere mir fünf Minuten lang die Schultern. Ohne Kommentar.' },
  { id: 'u22', ort: 'überall', q: 'Nenn zehn Dinge, für die du dankbar bist, ohne zu stocken. Bei einer Pause zählt es nicht.' },
  { id: 'u23', ort: 'überall', q: 'Iss oder trink das Nächste ausschließlich mit deiner schwachen Hand.' },
  { id: 'u24', ort: 'überall', q: 'Ruf jemanden aus deiner Familie an und sag ohne Vorwarnung, dass du ihn oder sie liebst. Dann leg auf.' },
  { id: 'u25', ort: 'überall', q: 'Schreib eine Fünf-Sterne-Bewertung über mich, als wäre ich ein Restaurant. Und lies sie vor.' },
  { id: 'u26', ort: 'überall', q: 'Mach eine Minute lang den Handstand an der Wand. Oder versuch es wenigstens ernsthaft.' },
  { id: 'u27', ort: 'überall', q: 'Erzähl mir von deinem letzten Traum, an den du dich erinnerst — mit allen peinlichen Details.' },
  { id: 'u28', ort: 'überall', q: 'Beschreibe mich fünf Minuten lang nur in der dritten Person, als wäre ich nicht da.' },
  { id: 'u29', ort: 'überall', q: 'Lass mich eine Regel für die nächste Stunde festlegen. Du hältst dich daran.' },
  { id: 'u30', ort: 'überall', q: 'Sag mir drei Dinge, die du an dir selbst magst — laut, ohne Relativieren.' },
  { id: 'u31', ort: 'überall', q: 'Erfinde einen Werbespot für mich. 30 Sekunden, mit Jingle.' },
  { id: 'u32', ort: 'überall', q: 'Schreib mir eine Liebeserklärung in genau zehn Wörtern. Vorlesen.' },
  { id: 'u33', ort: 'überall', q: 'Sprich bis zur nächsten Runde ausschließlich Englisch. Auch mit mir.' },
  { id: 'u34', ort: 'überall', q: 'Zeig mir dein Handy-Hintergrundbild und erklär, warum ausgerechnet das.' },
  { id: 'u35', ort: 'überall', q: 'Halte 60 Sekunden lang Blickkontakt mit mir. Ohne Reden, ohne Lachen.' },
  { id: 'u36', ort: 'überall', q: 'Tausch für die nächste halbe Stunde ein Kleidungsstück mit mir.' },
  { id: 'u37', ort: 'überall', q: 'Erzähl mir in zwei Minuten dein Leben, als wärst du ein Filmtrailer-Sprecher.' },
  { id: 'u38', ort: 'überall', q: 'Nenn ohne nachzudenken fünf Dinge, die du morgen anders machen willst — und mach mindestens eins davon.' },
  { id: 'u39', ort: 'überall', q: 'Lies mir deine letzten drei Suchanfragen vor.' },
  { id: 'u40', ort: 'überall', q: 'Sing ein Lied deiner Wahl komplett zu Ende. Ohne Text nachschauen.' },
  { id: 'u41', ort: 'überall', q: 'Schreib eine Nachricht an dich selbst in fünf Jahren und lies sie mir vor.' },
  { id: 'u42', ort: 'überall', q: 'Erklär mir dein Lieblingsthema drei Minuten lang so, als wäre ich fünf Jahre alt.' },
  { id: 'u43', ort: 'überall', q: 'Lass mich deinen Nachnamen in deinem Handy für den Rest des Urlaubs ändern — ich such ihn aus.' },
  { id: 'u44', ort: 'überall', q: 'Mach ein Foto von uns, auf dem wir beide absichtlich furchtbar aussehen. Es kommt in die Urlaubsgalerie.' },
  { id: 'u45', ort: 'überall', q: 'Steh auf und tanz 30 Sekunden — ohne Musik.' },

  // ── Unterwegs: Flughafen, Flieger, Bahn ─────────────────────────────────
  { id: 'f01', ort: 'flug', q: 'Frag das Bordpersonal nach seinem persönlichen Lieblingsort in Wien.' },
  { id: 'f02', ort: 'flug', q: 'Denk dir zu drei Mitreisenden in Sichtweite eine Lebensgeschichte aus und erzähl sie mir flüsternd.' },
  { id: 'f03', ort: 'flug', q: 'Bestell dein Getränk in einer Sprache, die du nicht sprichst. Mit Händen und Füßen.' },
  { id: 'f04', ort: 'flug', q: 'Schreib eine Postkarte an uns selbst, die wir in einem Jahr lesen. Ich darf sie nicht sehen.' },
  { id: 'f05', ort: 'flug', q: 'Mach ein Selfie von uns, auf dem wir beide so tun, als hätten wir gerade schlechte Nachrichten bekommen.' },
  { id: 'f06', ort: 'flug', q: 'Plane die ersten drei Stunden nach der Ankunft komplett allein. Ich erfahre nichts vorher und muss mitmachen.' },
  { id: 'f07', ort: 'flug', q: 'Sag der Person neben dir oder gegenüber ein ehrliches Kompliment.' },
  { id: 'f08', ort: 'flug', q: 'Lerne fünf Wörter Wienerisch und benutze sie ab jetzt konsequent.' },
  { id: 'f09', ort: 'flug', q: 'Erstelle eine Urlaubs-Playlist mit zehn Songs — in fünf Minuten, keine Korrektur danach.' },
  { id: 'f10', ort: 'flug', q: 'Zeig mir deinen Suchverlauf der letzten drei Tage.' },
  { id: 'f11', ort: 'flug', q: 'Bau aus dem, was du dabeihast, ein Geschenk für mich und überreiche es mit einer Rede.' },
  { id: 'f12', ort: 'flug', q: 'Schreib die drei Dinge auf, die dieser Urlaub unbedingt haben muss, und lies sie vor.' },
  { id: 'f13', ort: 'flug', q: 'Frag jemanden am Nachbarplatz, was das Beste ist, das ihm oder ihr diese Woche passiert ist.' },
  { id: 'f14', ort: 'flug', q: 'Beschreibe mir die Aussicht aus dem Fenster, als wärst du ein Reiseführer aus den 1950ern.' },
  { id: 'f15', ort: 'flug', q: 'Rate bei drei Mitreisenden den Beruf. Wenn du dich traust: frag nach, ob es stimmt.' },
  { id: 'f16', ort: 'flug', q: 'Bedanke dich beim Bordpersonal ausdrücklich und namentlich für den Service.' },
  { id: 'f17', ort: 'flug', q: 'Iss dein Bordessen komplett auf — auch das, was du nicht magst.' },
  { id: 'f18', ort: 'flug', q: 'Schreib in fünf Minuten eine Kurzgeschichte über eine Person, die du hier siehst, und lies sie vor.' },
  { id: 'f19', ort: 'flug', q: 'Lass mich dein Sitznachbar-Gespräch starten: ich gebe dir den ersten Satz vor.' },
  { id: 'f20', ort: 'flug', q: 'Mach eine Liste mit zehn Dingen, die du in Wien machen willst — und lass mich drei streichen.' },
  { id: 'f21', ort: 'flug', q: 'Nimm eine Sprachnachricht auf, in der du unseren Urlaub ankündigst wie einen Kinofilm. Schick sie jemandem.' },
  { id: 'f22', ort: 'flug', q: 'Frag eine fremde Person nach einem Buchtipp und notier ihn dir wirklich.' },
  { id: 'f23', ort: 'flug', q: 'Verzichte für die nächste Stunde komplett auf dein Handy. Es liegt bei mir.' },
  { id: 'f24', ort: 'flug', q: 'Erzähl mir, wie du unseren ersten gemeinsamen Urlaub in Erinnerung hast — Minute für Minute des ersten Tages.' },
  { id: 'f25', ort: 'flug', q: 'Such heraus, wie man in fünf Sprachen „Ich liebe dich“ sagt, und sag es mir in allen.' },

  // ── Draußen in der Stadt ────────────────────────────────────────────────
  { id: 's01', ort: 'stadt', q: 'Bestell deinen Kaffee im breitesten Wienerisch, das du hinbekommst.' },
  { id: 's02', ort: 'stadt', q: 'Frag eine fremde Person nach dem Weg zum Stephansdom — auch wenn ihr direkt davorsteht.' },
  { id: 's03', ort: 'stadt', q: 'Sing zwei Zeilen „Rock Me Amadeus“ so laut, dass mindestens eine fremde Person es hört.' },
  { id: 's04', ort: 'stadt', q: 'Tanz 15 Sekunden Walzer mit mir. Mitten auf dem Platz, wo wir gerade sind.' },
  { id: 's05', ort: 'stadt', q: 'Mach einer fremden Person ein ehrliches Kompliment und geh weiter, ohne auf eine Antwort zu warten.' },
  { id: 's06', ort: 'stadt', q: 'Bitte jemanden, ein Foto von uns zu machen — in der albernsten Pose, die dir einfällt.' },
  { id: 's07', ort: 'stadt', q: 'Kauf mir in zehn Minuten etwas für unter fünf Euro, das zu mir passt. Ich darf nicht mitkommen.' },
  { id: 's08', ort: 'stadt', q: 'Geh in einen Souvenirladen und probier den peinlichsten Hut an, den du findest. Foto ist Pflicht.' },
  { id: 's09', ort: 'stadt', q: 'Frag im Kaffeehaus nach dem Gericht, das die Bedienung selbst am liebsten isst — und bestell genau das.' },
  { id: 's10', ort: 'stadt', q: 'Sprich eine Wienerin oder einen Wiener an und lass dir einen Geheimtipp geben. Wir gehen heute noch hin.' },
  { id: 's11', ort: 'stadt', q: 'Ruf quer über den Platz meinen Namen und sag laut einen Satz, der mit „Ich liebe dich, weil …“ beginnt.' },
  { id: 's12', ort: 'stadt', q: 'Bestell im Kaffeehaus mit „Herr Ober, bitte!“ oder „Frau Ober, bitte!“ — mit voller Überzeugung.' },
  { id: 's13', ort: 'stadt', q: 'Führe mich zehn Minuten durch die Stadt und erfinde dabei Sehenswürdigkeiten samt Geschichte.' },
  { id: 's14', ort: 'stadt', q: 'Setz dich zu einer fremden Person auf eine Bank und stell drei ehrliche Fragen.' },
  { id: 's15', ort: 'stadt', q: 'Kauf eine Blume und schenk sie einer wildfremden Person.' },
  { id: 's16', ort: 'stadt', q: 'Bestell das Gericht, dessen Namen du nicht aussprechen kannst. Und iss es auf.' },
  { id: 's17', ort: 'stadt', q: 'Mach an der nächsten Kreuzung 30 Sekunden lang Statue. Egal wer zuschaut.' },
  { id: 's18', ort: 'stadt', q: 'Frag drei verschiedene Leute nach dem besten Schnitzel der Stadt und führ mich zum Sieger.' },
  { id: 's19', ort: 'stadt', q: 'Halte einer Statue eine zweiminütige Ansprache, als wäre sie ein alter Freund.' },
  { id: 's20', ort: 'stadt', q: 'Sprich die nächsten 20 Minuten mit allen in höchster Höflichkeit und per Sie — auch mit mir.' },
  { id: 's21', ort: 'stadt', q: 'Nimm die nächste Straßenbahn, die kommt — egal wohin. Wir steigen nach drei Stationen aus.' },
  { id: 's22', ort: 'stadt', q: 'Bring eine fremde Person innerhalb einer Minute zum Lachen.' },
  { id: 's23', ort: 'stadt', q: 'Lass dich von einer fremden Person fotografieren, während du so tust, als würdest du einen Preis gewinnen.' },
  { id: 's24', ort: 'stadt', q: 'Frag im nächsten Laden nach etwas, das es dort garantiert nicht gibt — todernst.' },
  { id: 's25', ort: 'stadt', q: 'Geh in eine Kirche und zünde eine Kerze an. Sag mir danach, wofür.' },
  { id: 's26', ort: 'stadt', q: 'Kauf uns beiden ein Eis in einer Sorte, die du noch nie probiert hast.' },
  { id: 's27', ort: 'stadt', q: 'Bitte eine fremde Person, uns eine Empfehlung fürs Abendessen zu geben. Wir gehen hin.' },
  { id: 's28', ort: 'stadt', q: 'Renn 20 Meter, als würdest du einen Bus verpassen — obwohl kein Bus da ist.' },
  { id: 's29', ort: 'stadt', q: 'Setz dich auf eine Parkbank und schreib in zehn Minuten ein Gedicht über diese Stadt. Vorlesen.' },
  { id: 's30', ort: 'stadt', q: 'Geh auf jemanden zu, der ein Instrument spielt, und gib etwas — mit einem echten Kompliment.' },
  { id: 's31', ort: 'stadt', q: 'Sprich mit mir die nächsten zehn Minuten nur in Filmzitaten.' },
  { id: 's32', ort: 'stadt', q: 'Lass eine fremde Person entscheiden, in welche Richtung wir als Nächstes gehen.' },
  { id: 's33', ort: 'stadt', q: 'Probier in einem Geschäft ein Kleidungsstück an, das überhaupt nicht zu dir passt, und zeig es mir.' },
  { id: 's34', ort: 'stadt', q: 'Frag eine ältere Person, wie Wien früher war. Hör mindestens fünf Minuten zu.' },
  { id: 's35', ort: 'stadt', q: 'Umarme mich mitten auf einem belebten Platz zehn Sekunden lang, ohne dich umzuschauen.' },
  { id: 's36', ort: 'stadt', q: 'Lauf die nächsten 100 Meter rückwärts. Ich führe dich.' },
  { id: 's37', ort: 'stadt', q: 'Kauf etwas auf einem Markt und handle den Preis — auch wenn man das hier nicht macht.' },
  { id: 's38', ort: 'stadt', q: 'Frag jemanden im Café, ob du kurz an seinem Tisch Platz nehmen darfst, und stell dich vor.' },
  { id: 's39', ort: 'stadt', q: 'Zähle laut alle Dinge auf, die du in diesem Moment schön findest. Mindestens fünfzehn.' },
  { id: 's40', ort: 'stadt', q: 'Frag im Museum oder an einer Kasse nach dem Lieblingsstück der Person hinter dem Tresen und schau es dir an.' },
  { id: 's41', ort: 'stadt', q: 'Kauf eine Zeitung oder Postkarte und lies mir eine Passage laut auf der Straße vor.' },
  { id: 's42', ort: 'stadt', q: 'Führ mich zehn Minuten lang mit geschlossenen Augen. Ich vertraue dir komplett.' },
  { id: 's43', ort: 'stadt', q: 'Sag der nächsten Bedienung, dass sie den besten Job der Welt hat — und begründe es.' },
  { id: 's44', ort: 'stadt', q: 'Mach fünf Fotos von Dingen, die dich an mich erinnern. Zeig sie mir und erklär jedes.' },
  { id: 's45', ort: 'stadt', q: 'Erfinde für die nächste halbe Stunde eine neue Identität. Wenn dich jemand fragt, bleibst du dabei.' },
  { id: 's46', ort: 'stadt', q: 'Frag eine fremde Person, was ihr Lieblingswort auf Deutsch ist. Benutze es heute noch dreimal.' },
  { id: 's47', ort: 'stadt', q: 'Verschenke einen Kaffee an die Person hinter dir in der Schlange.' },
  { id: 's48', ort: 'stadt', q: 'Stell dich vor ein Gemälde oder ein Denkmal und erklär mir laut, was es bedeutet — frei erfunden.' },
  { id: 's49', ort: 'stadt', q: 'Bestell in einem Lokal ausschließlich mit Handzeichen.' },
  { id: 's50', ort: 'stadt', q: 'Frag die nächste Person mit Hund, ob du den Hund streicheln darfst — und lern den Namen.' },

  // ── Abends: Bar, Restaurant, spät ───────────────────────────────────────
  { id: 'a01', ort: 'abend', q: 'Bestell für mich, ohne zu fragen. Ich esse, was kommt.' },
  { id: 'a02', ort: 'abend', q: 'Lass mich dein Getränk auswählen. Du trinkst es ohne Kommentar.' },
  { id: 'a03', ort: 'abend', q: 'Erhebe das Glas und halte einen Toast auf uns — laut genug, dass der Nachbartisch mithört.' },
  { id: 'a04', ort: 'abend', q: 'Frag die Person an der Bar nach dem Drink, den sie am liebsten macht, und bestell ihn.' },
  { id: 'a05', ort: 'abend', q: 'Lade ein fremdes Paar zu einem Gespräch an euren Tisch ein — für zehn Minuten.' },
  { id: 'a06', ort: 'abend', q: 'Sag mir vor allen, was du an mir am attraktivsten findest. In voller Lautstärke.' },
  { id: 'a07', ort: 'abend', q: 'Bestell etwas von der Karte, das du noch nie gegessen hast, und iss es komplett.' },
  { id: 'a08', ort: 'abend', q: 'Fordere mich zu einem Spiel deiner Wahl heraus. Verlierer zahlt die nächste Runde.' },
  { id: 'a09', ort: 'abend', q: 'Erzähl der Bedienung, dass wir heute etwas feiern — und erfinde was.' },
  { id: 'a10', ort: 'abend', q: 'Tanz mit mir, auch wenn niemand sonst tanzt. Mindestens einen ganzen Song.' },
  { id: 'a11', ort: 'abend', q: 'Sing oder summ ein Lied, bis ich errate, welches es ist.' },
  { id: 'a12', ort: 'abend', q: 'Schreib eine Nachricht auf eine Serviette und gib sie einer fremden Person. Etwas Nettes.' },
  { id: 'a13', ort: 'abend', q: 'Frag jemanden an der Bar nach der besten Geschichte, die er oder sie zu erzählen hat.' },
  { id: 'a14', ort: 'abend', q: 'Erzähl mir die peinlichste Geschichte aus deinem Leben — laut genug, dass es der Nachbartisch hört.' },
  { id: 'a15', ort: 'abend', q: 'Bestell das teuerste Ding auf der Karte — und iss oder trink es zur Hälfte, dann tauschen wir.' },
  { id: 'a16', ort: 'abend', q: 'Halte eine ernste Rede über mich, als wären wir auf einer Hochzeit. Zwei Minuten.' },
  { id: 'a17', ort: 'abend', q: 'Geh zu einem anderen Tisch und frag, was dort gerade gefeiert wird.' },
  { id: 'a18', ort: 'abend', q: 'Lass mich für den Rest des Abends deinen Spitznamen bestimmen. Du reagierst nur darauf.' },
  { id: 'a19', ort: 'abend', q: 'Bestell einen Nachtisch für den Nachbartisch — anonym.' },
  { id: 'a20', ort: 'abend', q: 'Frag jemanden nach der besten Bar der Stadt und wir gehen als Nächstes dorthin.' },
  { id: 'a21', ort: 'abend', q: 'Sag mir zehn Minuten lang zu allem, was ich vorschlage, Ja.' },
  { id: 'a22', ort: 'abend', q: 'Zeig mir dein Handy-Fotoalbum von heute und kommentiere jedes Bild in einem Satz.' },
  { id: 'a23', ort: 'abend', q: 'Frag die Bedienung, welchen Gast sie heute am sympathischsten fand — und warum.' },
  { id: 'a24', ort: 'abend', q: 'Erfinde einen Cocktail, gib ihm einen Namen nach mir und beschreib ihn der Bar.' },
  { id: 'a25', ort: 'abend', q: 'Erzähl mir, was du heute an mir gesehen hast, das du sonst übersiehst.' },
];
