// Wahrheitsfragen. Beide antworten immer, danach bewertet der oder die andere.
//
// { id, tiefe: 'leicht' | 'ehrlich' | 'tief', thema }

export const WAHRHEIT = [
  // ── Wir beide & der Anfang ──────────────────────────────────────────────
  { id: 'wir01', tiefe: 'leicht', thema: 'Wir beide', q: 'Was war dein allererster Gedanke, als du mich zum ersten Mal gesehen hast?' },
  { id: 'wir02', tiefe: 'leicht', thema: 'Wir beide', q: 'Welches gemeinsame Foto von uns magst du am liebsten — und warum genau das?' },
  { id: 'wir03', tiefe: 'leicht', thema: 'Wir beide', q: 'Was war der Moment, in dem du dachtest: das hier wird was Ernstes?' },
  { id: 'wir04', tiefe: 'leicht', thema: 'Wir beide', q: 'Welchen Spitznamen für mich hast du dir mal ausgedacht und nie ausgesprochen?' },
  { id: 'wir05', tiefe: 'leicht', thema: 'Wir beide', q: 'Was ist dein liebster Moment eines ganz normalen Tages mit mir?' },
  { id: 'wir06', tiefe: 'leicht', thema: 'Wir beide', q: 'Welches Kompliment von mir ist bei dir hängen geblieben?' },
  { id: 'wir07', tiefe: 'leicht', thema: 'Wir beide', q: 'Wann hast du dich zuletzt wegen mir richtig gefreut, ohne es zu zeigen?' },
  { id: 'wir08', tiefe: 'leicht', thema: 'Wir beide', q: 'Welche Angewohnheit von mir findest du insgeheim süß, obwohl du dich darüber beschwerst?' },
  { id: 'wir09', tiefe: 'leicht', thema: 'Wir beide', q: 'Wenn du mich in einem Satz jemandem beschreiben müsstest, der mich nie trifft — welcher Satz?' },
  { id: 'wir10', tiefe: 'leicht', thema: 'Wir beide', q: 'Welchen Streit von uns findest du im Nachhinein einfach nur komisch?' },
  { id: 'wir11', tiefe: 'leicht', thema: 'Wir beide', q: 'Was würdest du sofort wieder genauso machen, wenn wir unsere Hochzeit noch mal planen müssten?' },
  { id: 'wir12', tiefe: 'leicht', thema: 'Wir beide', q: 'Was würdest du an unserer Hochzeit ändern?' },
  { id: 'wir13', tiefe: 'ehrlich', thema: 'Wir beide', q: 'Wann hast du dich zuletzt von mir übersehen gefühlt?' },
  { id: 'wir14', tiefe: 'ehrlich', thema: 'Wir beide', q: 'Was sagst du über mich, wenn ich nicht dabei bin?' },
  { id: 'wir15', tiefe: 'ehrlich', thema: 'Wir beide', q: 'Was vermisst du an unserer Zeit vor der Ehe?' },
  { id: 'wir16', tiefe: 'ehrlich', thema: 'Wir beide', q: 'Welche Erwartung an mich hast du still aufgegeben?' },
  { id: 'wir17', tiefe: 'ehrlich', thema: 'Wir beide', q: 'Was war die letzte Situation, in der du dich für mich fremdgeschämt hast?' },
  { id: 'wir18', tiefe: 'ehrlich', thema: 'Wir beide', q: 'Welches Thema vermeiden wir beide konsequent?' },
  { id: 'wir19', tiefe: 'ehrlich', thema: 'Wir beide', q: 'Welche Kritik von mir hat dich mal richtig getroffen, und ich hab es nicht gemerkt?' },
  { id: 'wir20', tiefe: 'ehrlich', thema: 'Wir beide', q: 'Wofür bist du mir dankbar, ohne es je richtig gesagt zu haben?' },
  { id: 'wir21', tiefe: 'ehrlich', thema: 'Wir beide', q: 'Wofür hättest du dich bei mir längst entschuldigen sollen?' },
  { id: 'wir22', tiefe: 'ehrlich', thema: 'Wir beide', q: 'Wann hast du zuletzt „ist schon okay“ gesagt, obwohl es nicht okay war?' },
  { id: 'wir23', tiefe: 'tief', thema: 'Wir beide', q: 'In welchem Moment wusstest du, dass du mit mir alt werden willst?' },
  { id: 'wir24', tiefe: 'tief', thema: 'Wir beide', q: 'Wann hast du zuletzt an uns gezweifelt?' },
  { id: 'wir25', tiefe: 'tief', thema: 'Wir beide', q: 'Was glaubst du, verstehe ich an dir bis heute nicht?' },
  { id: 'wir26', tiefe: 'tief', thema: 'Wir beide', q: 'Welchen Teil von dir zeigst du nur mir — und welchen niemandem?' },
  { id: 'wir27', tiefe: 'tief', thema: 'Wir beide', q: 'Wenn du heute noch einmal Ja sagen müsstest — was würdest du diesmal dazusagen?' },
  { id: 'wir28', tiefe: 'tief', thema: 'Wir beide', q: 'Was brauchst du, um dich bei mir vollkommen sicher zu fühlen?' },
  { id: 'wir29', tiefe: 'tief', thema: 'Wir beide', q: 'Welche Version von uns in zehn Jahren wünschst du dir — und was müssten wir dafür ab morgen ändern?' },
  { id: 'wir30', tiefe: 'tief', thema: 'Wir beide', q: 'Was wäre aus dir geworden, wenn wir uns nie getroffen hätten?' },

  // ── Alltag & Reibung ────────────────────────────────────────────────────
  { id: 'alt01', tiefe: 'leicht', thema: 'Alltag', q: 'Welches Essen, das ich koche, magst du in Wahrheit weniger, als du zugibst?' },
  { id: 'alt02', tiefe: 'leicht', thema: 'Alltag', q: 'Welche Serie hast du heimlich ohne mich weitergeschaut?' },
  { id: 'alt03', tiefe: 'leicht', thema: 'Alltag', q: 'Was ist die harmloseste Lüge, die du mir diese Woche erzählt hast?' },
  { id: 'alt04', tiefe: 'leicht', thema: 'Alltag', q: 'Welche Hausarbeit schiebst du absichtlich so lange auf, bis ich sie mache?' },
  { id: 'alt05', tiefe: 'leicht', thema: 'Alltag', q: 'Was ist das Unordentlichste an dir, das du gut versteckst?' },
  { id: 'alt06', tiefe: 'leicht', thema: 'Alltag', q: 'Was würdest du an unserer Wohnung ändern, wenn Geld egal wäre?' },
  { id: 'alt07', tiefe: 'leicht', thema: 'Alltag', q: 'Welchen Gegenstand von mir würdest du am liebsten heimlich entsorgen?' },
  { id: 'alt08', tiefe: 'leicht', thema: 'Alltag', q: 'Wie oft am Tag denkst du an mich — ehrlich geschätzt?' },
  { id: 'alt09', tiefe: 'ehrlich', thema: 'Alltag', q: 'Welche meiner Angewohnheiten nervt dich wirklich — nicht die höfliche Antwort?' },
  { id: 'alt10', tiefe: 'ehrlich', thema: 'Alltag', q: 'Was tue ich, wenn ich gestresst bin, das dir zusetzt?' },
  { id: 'alt11', tiefe: 'ehrlich', thema: 'Alltag', q: 'In welchem Bereich unseres Lebens hast du das Gefühl, mehr zu tragen als ich?' },
  { id: 'alt12', tiefe: 'ehrlich', thema: 'Alltag', q: 'Was würdest du an unserer Rollenverteilung im Alltag ändern?' },
  { id: 'alt13', tiefe: 'ehrlich', thema: 'Alltag', q: 'Wann hast du dich zuletzt einsam gefühlt, obwohl ich im selben Raum war?' },
  { id: 'alt14', tiefe: 'ehrlich', thema: 'Alltag', q: 'Wie viel Zeit für dich allein bräuchtest du eigentlich pro Woche?' },
  { id: 'alt15', tiefe: 'ehrlich', thema: 'Alltag', q: 'Was an unserem Alltag langweilt dich?' },
  { id: 'alt16', tiefe: 'ehrlich', thema: 'Alltag', q: 'Welche Regel zwischen uns hältst du für überholt?' },
  { id: 'alt17', tiefe: 'ehrlich', thema: 'Alltag', q: 'Wann hast du zuletzt aufgeräumt, nur damit ich nichts sage?' },
  { id: 'alt18', tiefe: 'tief', thema: 'Alltag', q: 'Was fehlt dir in unserem gemeinsamen Leben am meisten?' },
  { id: 'alt19', tiefe: 'tief', thema: 'Alltag', q: 'Woran merkst du, dass es mir schlecht geht, bevor ich es sage?' },
  { id: 'alt20', tiefe: 'tief', thema: 'Alltag', q: 'Wenn wir ein Jahr lang alles anders machen dürften: was wäre das Erste?' },

  // ── Nähe & Körper ───────────────────────────────────────────────────────
  { id: 'nae01', tiefe: 'leicht', thema: 'Nähe', q: 'Welche Berührung von mir magst du am liebsten?' },
  { id: 'nae02', tiefe: 'leicht', thema: 'Nähe', q: 'Was findest du körperlich am attraktivsten an mir — und was hast du dabei noch nie gesagt?' },
  { id: 'nae03', tiefe: 'leicht', thema: 'Nähe', q: 'Wann hast du dich zuletzt so richtig zu mir hingezogen gefühlt?' },
  { id: 'nae04', tiefe: 'leicht', thema: 'Nähe', q: 'Welches Outfit von mir gefällt dir am besten?' },
  { id: 'nae05', tiefe: 'leicht', thema: 'Nähe', q: 'Wie sieht dein perfekter Abend zu zweit aus — im Detail?' },
  { id: 'nae06', tiefe: 'ehrlich', thema: 'Nähe', q: 'Wie zufrieden bist du gerade mit unserer Nähe — auf einer Skala von 1 bis 10, und was fehlt zur 10?' },
  { id: 'nae07', tiefe: 'ehrlich', thema: 'Nähe', q: 'Was wünschst du dir körperlich von mir, hast es aber nie so direkt gesagt?' },
  { id: 'nae08', tiefe: 'ehrlich', thema: 'Nähe', q: 'Was bringt dich am schnellsten dazu, dich mir wieder nah zu fühlen nach einem Streit?' },
  { id: 'nae09', tiefe: 'ehrlich', thema: 'Nähe', q: 'Woran merkst du, dass ich Abstand brauche — und wie geht es dir damit?' },
  { id: 'nae10', tiefe: 'ehrlich', thema: 'Nähe', q: 'Welche Zärtlichkeit fehlt dir im Alltag am meisten?' },
  { id: 'nae11', tiefe: 'ehrlich', thema: 'Nähe', q: 'Was hast du dir mal gewünscht und dich nicht getraut zu fragen?' },
  { id: 'nae12', tiefe: 'ehrlich', thema: 'Nähe', q: 'Wann warst du zuletzt eifersüchtig — und worauf genau?' },
  { id: 'nae13', tiefe: 'tief', thema: 'Nähe', q: 'Was macht dich bei mir wirklich verletzlich?' },
  { id: 'nae14', tiefe: 'tief', thema: 'Nähe', q: 'Wann fühlst du dich mir am nächsten — außerhalb vom Bett?' },
  { id: 'nae15', tiefe: 'tief', thema: 'Nähe', q: 'Was müsste passieren, damit du dich mir völlig ausliefern könntest?' },

  // ── Geld & Arbeit ───────────────────────────────────────────────────────
  { id: 'gel01', tiefe: 'leicht', thema: 'Geld & Arbeit', q: 'Wofür würdest du sofort 1.000 Euro ausgeben, wenn sie morgen da wären?' },
  { id: 'gel02', tiefe: 'leicht', thema: 'Geld & Arbeit', q: 'Welchen Beruf hättest du gern ausprobiert?' },
  { id: 'gel03', tiefe: 'leicht', thema: 'Geld & Arbeit', q: 'Was war dein sinnlosester Kauf der letzten zwei Jahre?' },
  { id: 'gel04', tiefe: 'ehrlich', thema: 'Geld & Arbeit', q: 'Wie viel Geld hast du zuletzt ausgegeben, ohne es zu erwähnen?' },
  { id: 'gel05', tiefe: 'ehrlich', thema: 'Geld & Arbeit', q: 'Was macht dich in deinem Job gerade unglücklich, und warum sagst du es nicht lauter?' },
  { id: 'gel06', tiefe: 'ehrlich', thema: 'Geld & Arbeit', q: 'Hast du Angst, dass wir irgendwann finanziell nicht klarkommen? Woran genau?' },
  { id: 'gel07', tiefe: 'ehrlich', thema: 'Geld & Arbeit', q: 'Findest du, wir gehen fair mit Geld um? Wo nicht?' },
  { id: 'gel08', tiefe: 'ehrlich', thema: 'Geld & Arbeit', q: 'Wie viel Arbeit ist zu viel Arbeit — bei mir, bei dir?' },
  { id: 'gel09', tiefe: 'ehrlich', thema: 'Geld & Arbeit', q: 'Für welchen beruflichen Traum würdest du Sicherheit aufgeben?' },
  { id: 'gel10', tiefe: 'tief', thema: 'Geld & Arbeit', q: 'Woran misst du beruflichen Erfolg — und erfüllst du dieses Maß gerade?' },
  { id: 'gel11', tiefe: 'tief', thema: 'Geld & Arbeit', q: 'Was würdest du arbeiten, wenn Geld keine Rolle spielte?' },
  { id: 'gel12', tiefe: 'tief', thema: 'Geld & Arbeit', q: 'Wovon in unserer finanziellen Zukunft hast du heimlich ein mulmiges Gefühl?' },

  // ── Familie & Herkunft ──────────────────────────────────────────────────
  { id: 'fam01', tiefe: 'leicht', thema: 'Familie', q: 'Welche Eigenschaft hast du eindeutig von deinen Eltern?' },
  { id: 'fam02', tiefe: 'leicht', thema: 'Familie', q: 'Welche Familientradition von dir möchtest du unbedingt behalten?' },
  { id: 'fam03', tiefe: 'leicht', thema: 'Familie', q: 'Was war das beste Essen deiner Kindheit?' },
  { id: 'fam04', tiefe: 'ehrlich', thema: 'Familie', q: 'Was an meiner Familie ist für dich anstrengender, als du zugibst?' },
  { id: 'fam05', tiefe: 'ehrlich', thema: 'Familie', q: 'Wo verteidigst du deine Familie, obwohl du mir insgeheim recht gibst?' },
  { id: 'fam06', tiefe: 'ehrlich', thema: 'Familie', q: 'Welche Erwartung deiner Familie an uns spürst du am stärksten?' },
  { id: 'fam07', tiefe: 'ehrlich', thema: 'Familie', q: 'Was möchtest du auf keinen Fall so machen wie deine Eltern?' },
  { id: 'fam08', tiefe: 'ehrlich', thema: 'Familie', q: 'Wem in deiner Familie stehst du weniger nah, als du zeigst?' },
  { id: 'fam09', tiefe: 'tief', thema: 'Familie', q: 'Was hast du deinen Eltern nie verziehen?' },
  { id: 'fam10', tiefe: 'tief', thema: 'Familie', q: 'Welche Wunde aus deiner Kindheit merkst du heute noch in unserer Beziehung?' },
  { id: 'fam11', tiefe: 'tief', thema: 'Familie', q: 'Was würdest du deinen Eltern heute gern sagen, wenn Zeit und Mut keine Rolle spielten?' },
  { id: 'fam12', tiefe: 'tief', thema: 'Familie', q: 'Welche Rolle hattest du als Kind in deiner Familie — und trägst du sie noch?' },

  // ── Zukunft & Kinder ────────────────────────────────────────────────────
  { id: 'zuk01', tiefe: 'leicht', thema: 'Zukunft', q: 'Wenn wir morgen auswandern müssten: wohin, und was nimmst du mit?' },
  { id: 'zuk02', tiefe: 'leicht', thema: 'Zukunft', q: 'Wie stellst du dir unser Zuhause in zehn Jahren vor?' },
  { id: 'zuk03', tiefe: 'leicht', thema: 'Zukunft', q: 'Welches Hobby willst du unbedingt noch anfangen?' },
  { id: 'zuk04', tiefe: 'ehrlich', thema: 'Zukunft', q: 'Was möchtest du unbedingt gemeinsam erlebt haben, bevor wir 40 sind?' },
  { id: 'zuk05', tiefe: 'ehrlich', thema: 'Zukunft', q: 'Wovor in unserer gemeinsamen Zukunft hast du am meisten Respekt?' },
  { id: 'zuk06', tiefe: 'ehrlich', thema: 'Zukunft', q: 'Was macht dir an deinem eigenen Älterwerden zu schaffen?' },
  { id: 'zuk07', tiefe: 'ehrlich', thema: 'Zukunft', q: 'Wie viel Veränderung verträgst du gerade in deinem Leben?' },
  { id: 'zuk08', tiefe: 'tief', thema: 'Zukunft', q: 'Wenn wir Kinder hätten oder bekämen: welche Eigenschaft von mir sollen sie unbedingt erben — und welche auf keinen Fall?' },
  { id: 'zuk09', tiefe: 'tief', thema: 'Zukunft', q: 'Was für ein Elternteil oder Mensch möchtest du für andere sein?' },
  { id: 'zuk10', tiefe: 'tief', thema: 'Zukunft', q: 'Was würdest du tun, wenn du wüsstest, du hättest noch genau ein Jahr?' },
  { id: 'zuk11', tiefe: 'tief', thema: 'Zukunft', q: 'Was soll man einmal über dich sagen, wenn du nicht mehr da bist?' },
  { id: 'zuk12', tiefe: 'tief', thema: 'Zukunft', q: 'Welchen Traum hast du aufgegeben, weil er nicht zu unserem Leben passt?' },

  // ── Ich selbst ──────────────────────────────────────────────────────────
  { id: 'ich01', tiefe: 'leicht', thema: 'Ich selbst', q: 'Was ist die peinlichste Musik, die du heimlich hörst?' },
  { id: 'ich02', tiefe: 'leicht', thema: 'Ich selbst', q: 'Welche Sache an dir würde mich überraschen, wenn ich sie erst heute erführe?' },
  { id: 'ich03', tiefe: 'leicht', thema: 'Ich selbst', q: 'Was hast du dir als Kind für dein Leben mit 30 vorgestellt?' },
  { id: 'ich04', tiefe: 'leicht', thema: 'Ich selbst', q: 'Worauf bist du unverhältnismäßig stolz?' },
  { id: 'ich05', tiefe: 'leicht', thema: 'Ich selbst', q: 'Welche völlig nutzlose Fähigkeit beherrschst du erstaunlich gut?' },
  { id: 'ich06', tiefe: 'leicht', thema: 'Ich selbst', q: 'Was ist dein größter Luxus im Alltag?' },
  { id: 'ich07', tiefe: 'ehrlich', thema: 'Ich selbst', q: 'Was findest du an dir selbst am schwersten zu akzeptieren?' },
  { id: 'ich08', tiefe: 'ehrlich', thema: 'Ich selbst', q: 'Welches Versprechen an dich selbst hast du in den letzten Jahren gebrochen?' },
  { id: 'ich09', tiefe: 'ehrlich', thema: 'Ich selbst', q: 'Wovor drückst du dich gerade?' },
  { id: 'ich10', tiefe: 'ehrlich', thema: 'Ich selbst', q: 'In welcher Situation bist du nicht die Person, die du sein willst?' },
  { id: 'ich11', tiefe: 'ehrlich', thema: 'Ich selbst', q: 'Wann hast du zuletzt gelogen, um gut dazustehen?' },
  { id: 'ich12', tiefe: 'ehrlich', thema: 'Ich selbst', q: 'Welche Freundschaft von dir tut dir eigentlich nicht gut?' },
  { id: 'ich13', tiefe: 'ehrlich', thema: 'Ich selbst', q: 'Was ist die unbequemste Wahrheit über dich selbst, die du inzwischen akzeptierst?' },
  { id: 'ich14', tiefe: 'ehrlich', thema: 'Ich selbst', q: 'Wofür beneidest du andere?' },
  { id: 'ich15', tiefe: 'ehrlich', thema: 'Ich selbst', q: 'Was tust du nur, weil andere es von dir erwarten?' },
  { id: 'ich16', tiefe: 'tief', thema: 'Ich selbst', q: 'Wovor hast du gerade in deinem Leben am meisten Angst?' },
  { id: 'ich17', tiefe: 'tief', thema: 'Ich selbst', q: 'Wann warst du zuletzt richtig stolz auf dich?' },
  { id: 'ich18', tiefe: 'tief', thema: 'Ich selbst', q: 'Woran misst du, ob dein Leben gerade gut läuft?' },
  { id: 'ich19', tiefe: 'tief', thema: 'Ich selbst', q: 'Was ist dein größtes ungelebtes Vorhaben?' },
  { id: 'ich20', tiefe: 'tief', thema: 'Ich selbst', q: 'Was ist das Mutigste, das du je gemacht hast?' },
  { id: 'ich21', tiefe: 'tief', thema: 'Ich selbst', q: 'Welche Entscheidung in deinem Leben bereust du am meisten?' },
  { id: 'ich22', tiefe: 'tief', thema: 'Ich selbst', q: 'Wofür würdest du dein jetziges Leben aufgeben?' },
  { id: 'ich23', tiefe: 'tief', thema: 'Ich selbst', q: 'Wann hast du dich zuletzt richtig lebendig gefühlt?' },
  { id: 'ich24', tiefe: 'tief', thema: 'Ich selbst', q: 'Was glaubst du über dich, das wahrscheinlich nicht stimmt?' },

  // ── Früher & Geheimnisse ────────────────────────────────────────────────
  { id: 'fru01', tiefe: 'leicht', thema: 'Früher', q: 'Was war deine peinlichste Phase als Teenager?' },
  { id: 'fru02', tiefe: 'leicht', thema: 'Früher', q: 'In wen warst du als Kind heimlich verliebt?' },
  { id: 'fru03', tiefe: 'leicht', thema: 'Früher', q: 'Welche Regel hast du als Jugendlicher am häufigsten gebrochen?' },
  { id: 'fru04', tiefe: 'leicht', thema: 'Früher', q: 'Was war dein schlimmstes Outfit, von dem es noch Fotos gibt?' },
  { id: 'fru05', tiefe: 'leicht', thema: 'Früher', q: 'Welchen Berufswunsch hattest du mit zehn?' },
  { id: 'fru06', tiefe: 'ehrlich', thema: 'Früher', q: 'Gibt es etwas, das du mir in den letzten sechs Monaten verschwiegen hast?' },
  { id: 'fru07', tiefe: 'ehrlich', thema: 'Früher', q: 'Was hast du in deinem Leben getan, wofür du dich heute noch schämst?' },
  { id: 'fru08', tiefe: 'ehrlich', thema: 'Früher', q: 'Welche Geschichte aus deiner Vergangenheit hast du mir geschönt erzählt?' },
  { id: 'fru09', tiefe: 'ehrlich', thema: 'Früher', q: 'Wen aus deiner Vergangenheit würdest du gern noch einmal treffen — und warum?' },
  { id: 'fru10', tiefe: 'ehrlich', thema: 'Früher', q: 'Was war dein größter Fehler vor unserer Zeit?' },
  { id: 'fru11', tiefe: 'tief', thema: 'Früher', q: 'Welchen Menschen aus deiner Vergangenheit trägst du immer noch mit dir herum?' },
  { id: 'fru12', tiefe: 'tief', thema: 'Früher', q: 'Was war der einsamste Moment deines Lebens?' },
  { id: 'fru13', tiefe: 'tief', thema: 'Früher', q: 'Wann hast du zuletzt geweint und es mir nicht erzählt?' },
  { id: 'fru14', tiefe: 'tief', thema: 'Früher', q: 'Was ist das Schwerste, das du je jemandem verziehen hast?' },
  { id: 'fru15', tiefe: 'tief', thema: 'Früher', q: 'Welcher Moment hat dich zu dem Menschen gemacht, der du heute bist?' },

  // ── Reisen & Abenteuer ──────────────────────────────────────────────────
  { id: 'rei01', tiefe: 'leicht', thema: 'Reisen', q: 'Welches Urlaubsbild hast du im Kopf, wenn du an „perfekt“ denkst?' },
  { id: 'rei02', tiefe: 'leicht', thema: 'Reisen', q: 'Was war unsere bisher beste gemeinsame Reise — und warum?' },
  { id: 'rei03', tiefe: 'leicht', thema: 'Reisen', q: 'Welches Reiseziel steht ganz oben auf deiner Liste und du hast es nie erwähnt?' },
  { id: 'rei04', tiefe: 'leicht', thema: 'Reisen', q: 'Was nervt dich beim Reisen mit mir?' },
  { id: 'rei05', tiefe: 'leicht', thema: 'Reisen', q: 'Bist du eher Planer oder Bauchmensch im Urlaub — und wie geht es dir mit mir dabei?' },
  { id: 'rei06', tiefe: 'ehrlich', thema: 'Reisen', q: 'Wann hast du dich in einem Urlaub mit mir gelangweilt?' },
  { id: 'rei07', tiefe: 'ehrlich', thema: 'Reisen', q: 'Welche Reise würdest du gern einmal allein machen?' },
  { id: 'rei08', tiefe: 'ehrlich', thema: 'Reisen', q: 'Was erhoffst du dir von genau diesem Urlaub?' },
  { id: 'rei09', tiefe: 'tief', thema: 'Reisen', q: 'Welcher Ort auf der Welt hat etwas in dir verändert?' },
  { id: 'rei10', tiefe: 'tief', thema: 'Reisen', q: 'Wenn wir ein Jahr frei hätten: was würdest du damit machen — ehrlich, nicht die Instagram-Antwort?' },
];
