// Allgemeinwissen. Die richtige Antwort steht hier immer an erster Stelle —
// die Engine mischt die Optionen beim Ziehen, damit die Position nichts verrät.
//
// { id, cat, q, o: [richtig, falsch, falsch, falsch] }

export const WISSEN = [
  // ── Wien & Österreich ───────────────────────────────────────────────────
  { id: 'at01', cat: 'Wien', q: 'Welcher Fluss fließt durch Wien?', o: ['Donau', 'Rhein', 'Elbe', 'Moldau'] },
  { id: 'at02', cat: 'Wien', q: 'Welcher große Komponist wurde in Wien geboren?', o: ['Franz Schubert', 'W. A. Mozart', 'Ludwig van Beethoven', 'Joseph Haydn'] },
  { id: 'at03', cat: 'Wien', q: 'Wie heißt der Dom mitten in der Wiener Innenstadt?', o: ['Stephansdom', 'Karlsdom', 'Michaelerkirche', 'Ruprechtskirche'] },
  { id: 'at04', cat: 'Wien', q: 'Welches Schloss war die Sommerresidenz der Habsburger?', o: ['Schönbrunn', 'Belvedere', 'Hofburg', 'Laxenburg'] },
  { id: 'at05', cat: 'Wien', q: 'Was ist eine „Wiener Melange“?', o: ['Kaffee mit aufgeschäumter Milch', 'Ein Mischbrot', 'Ein Kartenspiel', 'Ein Walzer'] },
  { id: 'at06', cat: 'Wien', q: 'Welcher Wiener Maler schuf „Der Kuss“?', o: ['Gustav Klimt', 'Egon Schiele', 'Oskar Kokoschka', 'Friedensreich Hundertwasser'] },
  { id: 'at07', cat: 'Wien', q: 'Welche Torte wurde 1832 in Wien erfunden?', o: ['Sachertorte', 'Linzer Torte', 'Esterházytorte', 'Malakofftorte'] },
  { id: 'at08', cat: 'Wien', q: 'Wie heißt Wiens Prachtstraße rund um die Innenstadt?', o: ['Ringstraße', 'Mariahilfer Straße', 'Kärntner Straße', 'Praterstraße'] },
  { id: 'at09', cat: 'Wien', q: 'Welcher Wiener schrieb „Die Traumdeutung“?', o: ['Sigmund Freud', 'Alfred Adler', 'Viktor Frankl', 'Carl Gustav Jung'] },
  { id: 'at10', cat: 'Wien', q: 'Welche Wiener Institution ist für ihre Lipizzaner berühmt?', o: ['Spanische Hofreitschule', 'Wiener Staatsoper', 'Albertina', 'Musikverein'] },
  { id: 'at11', cat: 'Wien', q: 'Was ist ein „Einspänner“ im Wiener Kaffeehaus?', o: ['Schwarzer Kaffee mit Schlagobers im Glas', 'Kaffee mit Rum', 'Doppelter Espresso', 'Kaffee mit Ei'] },
  { id: 'at12', cat: 'Wien', q: 'Was ist ein „Heuriger“?', o: ['Weinlokal mit jungem Wein', 'Ein Erntedankfest', 'Ein Straßenbahntyp', 'Ein Hefegebäck'] },
  { id: 'at13', cat: 'Wien', q: 'Wie sagt man in Wien zur Tüte?', o: ['Sackerl', 'Tüterl', 'Beutel', 'Packerl'] },
  { id: 'at14', cat: 'Wien', q: 'Welcher Künstler gestaltete das Hundertwasserhaus?', o: ['Friedensreich Hundertwasser', 'Otto Wagner', 'Adolf Loos', 'Josef Hoffmann'] },
  { id: 'at15', cat: 'Wien', q: 'In welchem Wiener Bezirk steht der Stephansdom?', o: ['1. Bezirk', '2. Bezirk', '7. Bezirk', '9. Bezirk'] },
  { id: 'at16', cat: 'Wien', q: 'Wie viele Bundesländer hat Österreich?', o: ['9', '8', '10', '7'] },
  { id: 'at17', cat: 'Wien', q: 'Welches Land grenzt NICHT an Österreich?', o: ['Kroatien', 'Slowenien', 'Ungarn', 'Slowakei'] },
  { id: 'at18', cat: 'Wien', q: 'Wie heißt der höchste Berg Österreichs?', o: ['Großglockner', 'Wildspitze', 'Großvenediger', 'Dachstein'] },
  { id: 'at19', cat: 'Wien', q: 'Welcher Österreicher landete 1985 mit „Rock Me Amadeus“ einen Welthit?', o: ['Falco', 'Udo Jürgens', 'Peter Alexander', 'Rainhard Fendrich'] },
  { id: 'at20', cat: 'Wien', q: 'Wie hieß die Frau von Kaiser Franz Joseph?', o: ['Elisabeth, genannt Sisi', 'Maria Theresia', 'Zita', 'Sophie'] },
  { id: 'at21', cat: 'Wien', q: 'Welche Kaiserin regierte Österreich 40 Jahre lang im 18. Jahrhundert?', o: ['Maria Theresia', 'Elisabeth I.', 'Katharina II.', 'Zita von Bourbon-Parma'] },
  { id: 'at22', cat: 'Wien', q: 'Auf welchem Hügel hat man den klassischen Blick über Wien?', o: ['Kahlenberg', 'Semmering', 'Schneeberg', 'Rax'] },
  { id: 'at23', cat: 'Wien', q: 'Wie heißt Wiens großer Vergnügungspark mit dem Riesenrad?', o: ['Prater', 'Donaupark', 'Augarten', 'Stadtpark'] },
  { id: 'at24', cat: 'Wien', q: 'Was bestellt man in Wien mit „a Krügerl“?', o: ['Ein halbes Bier', 'Einen Kaffee', 'Ein Glas Wein', 'Ein Wasser'] },
  { id: 'at25', cat: 'Wien', q: 'Wie heißt Wiens bekanntester Markt mit Essensständen?', o: ['Naschmarkt', 'Viktualienmarkt', 'Karmelitermarkt', 'Brunnenmarkt'] },
  { id: 'at26', cat: 'Wien', q: 'Welches Getränk gehört klassisch zum Wiener Kaffeehaus dazu?', o: ['Ein Glas Leitungswasser', 'Ein Schnaps', 'Ein Tee', 'Eine Limonade'] },
  { id: 'at27', cat: 'Wien', q: 'Wie nennt man in Österreich die Sahne?', o: ['Schlagobers', 'Rahmschaum', 'Sauerrahm', 'Topfen'] },
  { id: 'at28', cat: 'Wien', q: 'Was ist „Topfen“ in Österreich?', o: ['Quark', 'Hüttenkäse', 'Butter', 'Joghurt'] },
  { id: 'at29', cat: 'Wien', q: 'Welche Wiener Oper ist eines der berühmtesten Opernhäuser der Welt?', o: ['Wiener Staatsoper', 'Volksoper', 'Theater an der Wien', 'Burgtheater'] },
  { id: 'at30', cat: 'Wien', q: 'Welcher Walzer gilt als heimliche Hymne Österreichs?', o: ['An der schönen blauen Donau', 'Kaiserwalzer', 'Frühlingsstimmen', 'Wiener Blut'] },
  { id: 'at31', cat: 'Wien', q: 'Wie heißt das Wiener Neujahrskonzert-Orchester?', o: ['Wiener Philharmoniker', 'Wiener Symphoniker', 'Tonkünstler-Orchester', 'RSO Wien'] },
  { id: 'at32', cat: 'Wien', q: 'Welcher Wiener Architekt prägte den Jugendstil mit der Kirche am Steinhof?', o: ['Otto Wagner', 'Adolf Loos', 'Camillo Sitte', 'Theophil Hansen'] },

  // ── Geografie ───────────────────────────────────────────────────────────
  { id: 'geo01', cat: 'Geografie', q: 'Wie heißt die Hauptstadt Australiens?', o: ['Canberra', 'Sydney', 'Melbourne', 'Perth'] },
  { id: 'geo02', cat: 'Geografie', q: 'Welches Land hat die längste Küstenlinie der Welt?', o: ['Kanada', 'Russland', 'Indonesien', 'Australien'] },
  { id: 'geo03', cat: 'Geografie', q: 'Welcher ist der tiefste See der Erde?', o: ['Baikalsee', 'Tanganjikasee', 'Titicacasee', 'Genfersee'] },
  { id: 'geo04', cat: 'Geografie', q: 'Welcher Fluss führt das meiste Wasser der Welt?', o: ['Amazonas', 'Nil', 'Jangtse', 'Mississippi'] },
  { id: 'geo05', cat: 'Geografie', q: 'Wie heißt die Hauptstadt Kanadas?', o: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'] },
  { id: 'geo06', cat: 'Geografie', q: 'Welches Meer liegt zwischen Italien und Kroatien?', o: ['Adria', 'Ägäis', 'Tyrrhenisches Meer', 'Ionisches Meer'] },
  { id: 'geo07', cat: 'Geografie', q: 'In welchem Land liegt Machu Picchu?', o: ['Peru', 'Bolivien', 'Ecuador', 'Chile'] },
  { id: 'geo08', cat: 'Geografie', q: 'Welche Großstadt liegt auf zwei Kontinenten?', o: ['Istanbul', 'Kairo', 'Athen', 'Moskau'] },
  { id: 'geo09', cat: 'Geografie', q: 'Wie viele Zeitzonen hat Russland?', o: ['11', '7', '9', '14'] },
  { id: 'geo10', cat: 'Geografie', q: 'Welches ist das flächenmäßig kleinste Land der Welt?', o: ['Vatikanstadt', 'Monaco', 'San Marino', 'Liechtenstein'] },
  { id: 'geo11', cat: 'Geografie', q: 'Wie heißt die Hauptstadt Neuseelands?', o: ['Wellington', 'Auckland', 'Christchurch', 'Dunedin'] },
  { id: 'geo12', cat: 'Geografie', q: 'Welcher Ozean ist der größte?', o: ['Pazifik', 'Atlantik', 'Indischer Ozean', 'Arktischer Ozean'] },
  { id: 'geo13', cat: 'Geografie', q: 'In welchem Gebirge liegt der Mount Everest?', o: ['Himalaya', 'Karakorum', 'Anden', 'Alpen'] },
  { id: 'geo14', cat: 'Geografie', q: 'Welches Land hat heute die meisten Einwohner?', o: ['Indien', 'China', 'USA', 'Indonesien'] },
  { id: 'geo15', cat: 'Geografie', q: 'Auf welchem Kontinent liegt die Sahara?', o: ['Afrika', 'Asien', 'Australien', 'Südamerika'] },
  { id: 'geo16', cat: 'Geografie', q: 'Wie heißt die Währung der Schweiz?', o: ['Schweizer Franken', 'Euro', 'Krone', 'Gulden'] },
  { id: 'geo17', cat: 'Geografie', q: 'Welche Wüste ist die größte Sandwüste der Erde?', o: ['Sahara', 'Gobi', 'Kalahari', 'Atacama'] },
  { id: 'geo18', cat: 'Geografie', q: 'Welches Land besteht aus über 17.000 Inseln?', o: ['Indonesien', 'Philippinen', 'Japan', 'Malediven'] },
  { id: 'geo19', cat: 'Geografie', q: 'Durch welches Land fließt die Donau NICHT?', o: ['Polen', 'Ungarn', 'Serbien', 'Rumänien'] },
  { id: 'geo20', cat: 'Geografie', q: 'Wie heißt die Hauptstadt von Marokko?', o: ['Rabat', 'Casablanca', 'Marrakesch', 'Fès'] },
  { id: 'geo21', cat: 'Geografie', q: 'Welcher Kanal verbindet Mittelmeer und Rotes Meer?', o: ['Suezkanal', 'Panamakanal', 'Kieler Kanal', 'Korinth-Kanal'] },
  { id: 'geo22', cat: 'Geografie', q: 'Welches europäische Land hat die meisten Vulkane?', o: ['Island', 'Italien', 'Griechenland', 'Spanien'] },
  { id: 'geo23', cat: 'Geografie', q: 'In welchem Land liegt die Stadt Marrakesch?', o: ['Marokko', 'Tunesien', 'Algerien', 'Ägypten'] },
  { id: 'geo24', cat: 'Geografie', q: 'Welches Land wird „Land der tausend Seen“ genannt?', o: ['Finnland', 'Schweden', 'Kanada', 'Estland'] },
  { id: 'geo25', cat: 'Geografie', q: 'Welche Stadt ist die nördlichste Hauptstadt der Welt?', o: ['Reykjavík', 'Oslo', 'Helsinki', 'Stockholm'] },
  { id: 'geo26', cat: 'Geografie', q: 'Wie heißt der höchste Wasserfall der Erde?', o: ['Salto Ángel', 'Niagarafälle', 'Victoriafälle', 'Iguazú'] },
  { id: 'geo27', cat: 'Geografie', q: 'Welches Land hat als Flagge einen roten Punkt auf Weiß?', o: ['Japan', 'Bangladesch', 'Palau', 'Südkorea'] },
  { id: 'geo28', cat: 'Geografie', q: 'Auf welcher Insel liegt der Ätna?', o: ['Sizilien', 'Sardinien', 'Kreta', 'Korsika'] },
  { id: 'geo29', cat: 'Geografie', q: 'Welcher See ist der größte der Erde (nach Fläche)?', o: ['Kaspisches Meer', 'Oberer See', 'Baikalsee', 'Victoriasee'] },
  { id: 'geo30', cat: 'Geografie', q: 'Welche Stadt trägt den Beinamen „die Ewige Stadt“?', o: ['Rom', 'Athen', 'Jerusalem', 'Istanbul'] },

  // ── Geschichte ──────────────────────────────────────────────────────────
  { id: 'his01', cat: 'Geschichte', q: 'In welchem Jahr fiel die Berliner Mauer?', o: ['1989', '1987', '1991', '1993'] },
  { id: 'his02', cat: 'Geschichte', q: 'Wer war der erste Mensch im Weltall?', o: ['Juri Gagarin', 'Neil Armstrong', 'Alan Shepard', 'German Titow'] },
  { id: 'his03', cat: 'Geschichte', q: 'In welchem Jahr sank die Titanic?', o: ['1912', '1905', '1918', '1923'] },
  { id: 'his04', cat: 'Geschichte', q: 'Welcher Krieg begann 1914?', o: ['Erster Weltkrieg', 'Zweiter Weltkrieg', 'Krimkrieg', 'Spanischer Bürgerkrieg'] },
  { id: 'his05', cat: 'Geschichte', q: 'Wer erreichte 1492 im Auftrag Spaniens Amerika?', o: ['Christoph Kolumbus', 'Vasco da Gama', 'Ferdinand Magellan', 'Amerigo Vespucci'] },
  { id: 'his06', cat: 'Geschichte', q: 'Welche antike Stadt wurde vom Vesuv verschüttet?', o: ['Pompeji', 'Karthago', 'Troja', 'Ephesos'] },
  { id: 'his07', cat: 'Geschichte', q: 'Wer war die erste Frau, die einen Nobelpreis erhielt?', o: ['Marie Curie', 'Rosalind Franklin', 'Lise Meitner', 'Ada Lovelace'] },
  { id: 'his08', cat: 'Geschichte', q: 'Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?', o: ['Konrad Adenauer', 'Willy Brandt', 'Ludwig Erhard', 'Helmut Schmidt'] },
  { id: 'his09', cat: 'Geschichte', q: 'In welchem Jahrhundert lebte Mozart?', o: ['18. Jahrhundert', '17. Jahrhundert', '19. Jahrhundert', '16. Jahrhundert'] },
  { id: 'his10', cat: 'Geschichte', q: 'Welche Dynastie regierte jahrhundertelang von Wien aus?', o: ['Habsburger', 'Hohenzollern', 'Bourbonen', 'Windsors'] },
  { id: 'his11', cat: 'Geschichte', q: 'Wer erfand um 1450 den Buchdruck mit beweglichen Lettern in Europa?', o: ['Johannes Gutenberg', 'Martin Luther', 'Leonardo da Vinci', 'William Caxton'] },
  { id: 'his12', cat: 'Geschichte', q: 'In welchem Jahr landeten erstmals Menschen auf dem Mond?', o: ['1969', '1965', '1972', '1961'] },
  { id: 'his13', cat: 'Geschichte', q: 'Wer war der erste Kaiser Roms?', o: ['Augustus', 'Julius Caesar', 'Nero', 'Trajan'] },
  { id: 'his14', cat: 'Geschichte', q: 'Welches Land schenkte den USA die Freiheitsstatue?', o: ['Frankreich', 'England', 'Spanien', 'Niederlande'] },
  { id: 'his15', cat: 'Geschichte', q: 'Wer war Anführerin der französischen Truppen im Hundertjährigen Krieg?', o: ['Jeanne d’Arc', 'Marie Antoinette', 'Katharina von Medici', 'Eleonore von Aquitanien'] },
  { id: 'his16', cat: 'Geschichte', q: 'In welchem Jahr begann die Französische Revolution?', o: ['1789', '1776', '1804', '1815'] },
  { id: 'his17', cat: 'Geschichte', q: 'Wer schrieb die 95 Thesen und löste die Reformation aus?', o: ['Martin Luther', 'Johannes Calvin', 'Ulrich Zwingli', 'Thomas Müntzer'] },
  { id: 'his18', cat: 'Geschichte', q: 'Welches Volk baute die Pyramiden von Gizeh?', o: ['Die alten Ägypter', 'Die Sumerer', 'Die Nubier', 'Die Phönizier'] },
  { id: 'his19', cat: 'Geschichte', q: 'Wo wurde Napoleon 1815 endgültig geschlagen?', o: ['Waterloo', 'Leipzig', 'Austerlitz', 'Borodino'] },
  { id: 'his20', cat: 'Geschichte', q: 'Welche Mauer wurde 1961 gebaut?', o: ['Die Berliner Mauer', 'Die Chinesische Mauer', 'Der Limes', 'Der Hadrianswall'] },
  { id: 'his21', cat: 'Geschichte', q: 'Wer war die letzte Pharaonin Ägyptens?', o: ['Kleopatra VII.', 'Nofretete', 'Hatschepsut', 'Nitokris'] },
  { id: 'his22', cat: 'Geschichte', q: 'Welches Schiff brachte 1620 englische Siedler nach Amerika?', o: ['Mayflower', 'Santa Maria', 'Beagle', 'Endeavour'] },
  { id: 'his23', cat: 'Geschichte', q: 'Wer führte den gewaltlosen Widerstand in Indien an?', o: ['Mahatma Gandhi', 'Jawaharlal Nehru', 'Subhas Chandra Bose', 'B. R. Ambedkar'] },
  { id: 'his24', cat: 'Geschichte', q: 'Welcher Vertrag beendete 1919 formal den Ersten Weltkrieg mit Deutschland?', o: ['Vertrag von Versailles', 'Vertrag von Trianon', 'Vertrag von Saint-Germain', 'Vertrag von Rom'] },
  { id: 'his25', cat: 'Geschichte', q: 'Wer war der erste Präsident der USA?', o: ['George Washington', 'Thomas Jefferson', 'John Adams', 'Benjamin Franklin'] },
  { id: 'his26', cat: 'Geschichte', q: 'In welchem Jahr wurde die Europäische Union durch den Vertrag von Maastricht gegründet?', o: ['1992', '1985', '1999', '2004'] },
  { id: 'his27', cat: 'Geschichte', q: 'Welche Seuche wütete im 14. Jahrhundert in Europa?', o: ['Die Pest', 'Die Cholera', 'Die Pocken', 'Die Spanische Grippe'] },
  { id: 'his28', cat: 'Geschichte', q: 'Wer war Südafrikas erster schwarzer Präsident?', o: ['Nelson Mandela', 'Desmond Tutu', 'Thabo Mbeki', 'Jacob Zuma'] },

  // ── Natur & Körper ──────────────────────────────────────────────────────
  { id: 'nat01', cat: 'Natur', q: 'Wie viele Knochen hat ein erwachsener Mensch?', o: ['206', '186', '224', '256'] },
  { id: 'nat02', cat: 'Natur', q: 'Welches Element hat das Symbol „Au“?', o: ['Gold', 'Silber', 'Aluminium', 'Kupfer'] },
  { id: 'nat03', cat: 'Natur', q: 'Was misst die Richterskala?', o: ['Erdbebenstärke', 'Windstärke', 'Lautstärke', 'Radioaktivität'] },
  { id: 'nat04', cat: 'Natur', q: 'Wie schnell ist Licht ungefähr?', o: ['300.000 km/s', '30.000 km/s', '3 Mio. km/s', '3.000 km/s'] },
  { id: 'nat05', cat: 'Natur', q: 'Welches Organ produziert Insulin?', o: ['Bauchspeicheldrüse', 'Leber', 'Niere', 'Milz'] },
  { id: 'nat06', cat: 'Natur', q: 'Welches Gas nehmen Pflanzen bei der Fotosynthese auf?', o: ['Kohlendioxid', 'Sauerstoff', 'Stickstoff', 'Methan'] },
  { id: 'nat07', cat: 'Natur', q: 'Was transportieren die roten Blutkörperchen?', o: ['Sauerstoff', 'Zucker', 'Hormone', 'Fett'] },
  { id: 'nat08', cat: 'Natur', q: 'Welches Vitamin bildet der Körper mithilfe von Sonnenlicht?', o: ['Vitamin D', 'Vitamin C', 'Vitamin B12', 'Vitamin K'] },
  { id: 'nat09', cat: 'Natur', q: 'Wie viele Chromosomenpaare hat der Mensch?', o: ['23', '21', '25', '46'] },
  { id: 'nat10', cat: 'Natur', q: 'In welcher Einheit misst man Lautstärke?', o: ['Dezibel', 'Hertz', 'Watt', 'Lumen'] },
  { id: 'nat11', cat: 'Natur', q: 'Woraus besteht Wasser chemisch?', o: ['Wasserstoff und Sauerstoff', 'Wasserstoff und Stickstoff', 'Sauerstoff und Kohlenstoff', 'Helium und Sauerstoff'] },
  { id: 'nat12', cat: 'Natur', q: 'Welches ist das härteste natürliche Material?', o: ['Diamant', 'Quarz', 'Stahl', 'Titan'] },
  { id: 'nat13', cat: 'Natur', q: 'Welches Organ ist das größte des Menschen?', o: ['Die Haut', 'Die Leber', 'Die Lunge', 'Der Darm'] },
  { id: 'nat14', cat: 'Natur', q: 'Wie viele Kammern hat das menschliche Herz?', o: ['4', '2', '3', '6'] },
  { id: 'nat15', cat: 'Natur', q: 'Bei wie viel Grad Celsius siedet Wasser auf Meereshöhe?', o: ['100', '90', '110', '80'] },
  { id: 'nat16', cat: 'Natur', q: 'Welches Element ist im Universum am häufigsten?', o: ['Wasserstoff', 'Helium', 'Sauerstoff', 'Kohlenstoff'] },
  { id: 'nat17', cat: 'Natur', q: 'Was entsteht, wenn ein Stern sehr großer Masse kollabiert?', o: ['Ein Schwarzes Loch', 'Ein Komet', 'Ein Asteroid', 'Ein Nebelmond'] },
  { id: 'nat18', cat: 'Natur', q: 'Wie nennt man die Angst vor engen Räumen?', o: ['Klaustrophobie', 'Agoraphobie', 'Akrophobie', 'Arachnophobie'] },
  { id: 'nat19', cat: 'Natur', q: 'Welcher Muskel ist der stärkste im Verhältnis zu seiner Größe?', o: ['Der Kaumuskel', 'Der Bizeps', 'Das Herz', 'Die Wade'] },
  { id: 'nat20', cat: 'Natur', q: 'Was bedeutet die Abkürzung DNA?', o: ['Desoxyribonukleinsäure', 'Dinatriumacetat', 'Dendritische Nervenachse', 'Doppelnukleare Aminosäure'] },
  { id: 'nat21', cat: 'Natur', q: 'Wie viele Flächen hat ein Dodekaeder?', o: ['12', '10', '20', '8'] },
  { id: 'nat22', cat: 'Natur', q: 'Welche Blutgruppe gilt als Universalspender (rote Blutkörperchen)?', o: ['0 negativ', 'AB positiv', 'A positiv', 'B negativ'] },
  { id: 'nat23', cat: 'Natur', q: 'Welche Farbe hat Chlorophyll?', o: ['Grün', 'Rot', 'Blau', 'Gelb'] },
  { id: 'nat24', cat: 'Natur', q: 'Woraus besteht der größte Teil der Erdatmosphäre?', o: ['Stickstoff', 'Sauerstoff', 'Kohlendioxid', 'Argon'] },
  { id: 'nat25', cat: 'Natur', q: 'Wie nennt man die Wissenschaft von den Erdbeben?', o: ['Seismologie', 'Vulkanologie', 'Geodäsie', 'Meteorologie'] },
  { id: 'nat26', cat: 'Natur', q: 'Was ist ein Tsunami?', o: ['Eine durch Erdbeben ausgelöste Meereswelle', 'Ein tropischer Wirbelsturm', 'Eine Springflut', 'Ein Unterwasservulkan'] },

  // ── Tiere ───────────────────────────────────────────────────────────────
  { id: 'tie01', cat: 'Tiere', q: 'Wie viele Herzen hat ein Oktopus?', o: ['3', '1', '2', '5'] },
  { id: 'tie02', cat: 'Tiere', q: 'Welches Tier ist das größte der Erde?', o: ['Blauwal', 'Afrikanischer Elefant', 'Pottwal', 'Giraffe'] },
  { id: 'tie03', cat: 'Tiere', q: 'Welches Landtier ist das schnellste?', o: ['Gepard', 'Löwe', 'Gabelbock', 'Pferd'] },
  { id: 'tie04', cat: 'Tiere', q: 'Wie viele Beine hat eine Spinne?', o: ['8', '6', '10', '12'] },
  { id: 'tie05', cat: 'Tiere', q: 'Welches Tier schläft im Stehen und mit einem offenen Auge?', o: ['Die Giraffe schläft stehend', 'Der Wolf', 'Der Igel', 'Das Wildschwein'] },
  { id: 'tie06', cat: 'Tiere', q: 'Welcher Vogel kann rückwärts fliegen?', o: ['Kolibri', 'Adler', 'Specht', 'Schwalbe'] },
  { id: 'tie07', cat: 'Tiere', q: 'Wie nennt man eine Gruppe von Löwen?', o: ['Rudel', 'Schwarm', 'Herde', 'Meute'] },
  { id: 'tie08', cat: 'Tiere', q: 'Welches Tier hat den längsten Winterschlaf?', o: ['Der Siebenschläfer', 'Der Braunbär', 'Das Eichhörnchen', 'Der Dachs'] },
  { id: 'tie09', cat: 'Tiere', q: 'Welches Tier legt als einziges Säugetier Eier?', o: ['Das Schnabeltier', 'Das Gürteltier', 'Das Faultier', 'Der Ameisenbär'] },
  { id: 'tie10', cat: 'Tiere', q: 'Wie viele Mägen hat eine Kuh?', o: ['4 Magenabteilungen', '2', '3', '1'] },
  { id: 'tie11', cat: 'Tiere', q: 'Welches Tier gilt als das giftigste der Welt?', o: ['Die Seewespe (Würfelqualle)', 'Die Kobra', 'Der Skorpion', 'Der Kugelfisch'] },
  { id: 'tie12', cat: 'Tiere', q: 'Welcher Fisch kann sein Geschlecht wechseln?', o: ['Der Clownfisch', 'Der Hering', 'Der Karpfen', 'Der Hecht'] },
  { id: 'tie13', cat: 'Tiere', q: 'Was fressen Pandas fast ausschließlich?', o: ['Bambus', 'Fisch', 'Beeren', 'Gras'] },
  { id: 'tie14', cat: 'Tiere', q: 'Welches Tier hat Fingerabdrücke, die menschlichen ähneln?', o: ['Der Koala', 'Der Delfin', 'Der Orang-Utan-Fuß', 'Das Kaninchen'] },
  { id: 'tie15', cat: 'Tiere', q: 'Wie lange ist eine Elefantenkuh ungefähr trächtig?', o: ['Etwa 22 Monate', 'Etwa 9 Monate', 'Etwa 12 Monate', 'Etwa 30 Monate'] },
  { id: 'tie16', cat: 'Tiere', q: 'Welches Insekt produziert Honig?', o: ['Die Honigbiene', 'Die Wespe', 'Die Hummel', 'Die Ameise'] },
  { id: 'tie17', cat: 'Tiere', q: 'Welches Tier kann seine Farbe zur Tarnung ändern?', o: ['Das Chamäleon', 'Der Leguan', 'Der Gecko', 'Die Eidechse'] },
  { id: 'tie18', cat: 'Tiere', q: 'Wie viele Zähne hat ein erwachsener Mensch normalerweise?', o: ['32', '28', '30', '36'] },

  // ── Weltraum & Technik ──────────────────────────────────────────────────
  { id: 'tec01', cat: 'Technik', q: 'Welcher Planet ist der Sonne am nächsten?', o: ['Merkur', 'Venus', 'Mars', 'Erde'] },
  { id: 'tec02', cat: 'Technik', q: 'Welcher ist der größte Planet unseres Sonnensystems?', o: ['Jupiter', 'Saturn', 'Neptun', 'Uranus'] },
  { id: 'tec03', cat: 'Technik', q: 'Welcher Planet wird „der rote Planet“ genannt?', o: ['Mars', 'Venus', 'Merkur', 'Jupiter'] },
  { id: 'tec04', cat: 'Technik', q: 'Wie heißt unsere Galaxie?', o: ['Milchstraße', 'Andromeda', 'Sombrero', 'Triangulum'] },
  { id: 'tec05', cat: 'Technik', q: 'Wie lange braucht das Licht von der Sonne zur Erde?', o: ['Etwa 8 Minuten', 'Etwa 8 Sekunden', 'Etwa 1 Stunde', 'Etwa 1 Tag'] },
  { id: 'tec06', cat: 'Technik', q: 'Wer entwickelte die Relativitätstheorie?', o: ['Albert Einstein', 'Isaac Newton', 'Niels Bohr', 'Max Planck'] },
  { id: 'tec07', cat: 'Technik', q: 'Wofür steht „WWW“?', o: ['World Wide Web', 'Wide World Wire', 'Web Wide World', 'World Web Wire'] },
  { id: 'tec08', cat: 'Technik', q: 'Wer gründete Microsoft mit?', o: ['Bill Gates', 'Steve Jobs', 'Larry Page', 'Michael Dell'] },
  { id: 'tec09', cat: 'Technik', q: 'Was bedeutet „HTTP“ am Anfang einer Webadresse?', o: ['Hypertext Transfer Protocol', 'High Transfer Text Protocol', 'Hyperlink Text Transport', 'Home Text Transfer Path'] },
  { id: 'tec10', cat: 'Technik', q: 'Wie viele Bit hat ein Byte?', o: ['8', '4', '16', '10'] },
  { id: 'tec11', cat: 'Technik', q: 'Welches Unternehmen entwickelte das Betriebssystem Android?', o: ['Google', 'Apple', 'Samsung', 'Microsoft'] },
  { id: 'tec12', cat: 'Technik', q: 'Wer erfand das Telefon (mit dem ersten Patent)?', o: ['Alexander Graham Bell', 'Thomas Edison', 'Nikola Tesla', 'Guglielmo Marconi'] },
  { id: 'tec13', cat: 'Technik', q: 'Wie heißt der erste künstliche Erdsatellit?', o: ['Sputnik 1', 'Explorer 1', 'Vostok 1', 'Apollo 1'] },
  { id: 'tec14', cat: 'Technik', q: 'Welche Firma stellt den Prozessor „Snapdragon“ her?', o: ['Qualcomm', 'Intel', 'AMD', 'Nvidia'] },
  { id: 'tec15', cat: 'Technik', q: 'Was misst ein Barometer?', o: ['Luftdruck', 'Temperatur', 'Luftfeuchtigkeit', 'Windgeschwindigkeit'] },
  { id: 'tec16', cat: 'Technik', q: 'Wer gilt als erste Programmiererin der Geschichte?', o: ['Ada Lovelace', 'Grace Hopper', 'Hedy Lamarr', 'Margaret Hamilton'] },
  { id: 'tec17', cat: 'Technik', q: 'Wie viele Planeten hat unser Sonnensystem heute offiziell?', o: ['8', '9', '7', '10'] },
  { id: 'tec18', cat: 'Technik', q: 'Was ist ein „Lichtjahr“?', o: ['Eine Entfernung', 'Eine Zeitspanne', 'Eine Helligkeit', 'Eine Geschwindigkeit'] },
  { id: 'tec19', cat: 'Technik', q: 'Welches Metall ist bei Zimmertemperatur flüssig?', o: ['Quecksilber', 'Blei', 'Zinn', 'Natrium'] },
  { id: 'tec20', cat: 'Technik', q: 'Wer erfand die Glühlampe zur Marktreife?', o: ['Thomas Edison', 'Nikola Tesla', 'James Watt', 'Michael Faraday'] },

  // ── Kunst & Literatur ───────────────────────────────────────────────────
  { id: 'kul01', cat: 'Kultur', q: 'Wer malte die Mona Lisa?', o: ['Leonardo da Vinci', 'Michelangelo', 'Raffael', 'Tizian'] },
  { id: 'kul02', cat: 'Kultur', q: 'Wer schrieb „Romeo und Julia“?', o: ['William Shakespeare', 'Christopher Marlowe', 'Molière', 'Johann Wolfgang von Goethe'] },
  { id: 'kul03', cat: 'Kultur', q: 'Wer schrieb „Faust“?', o: ['Goethe', 'Schiller', 'Lessing', 'Heine'] },
  { id: 'kul04', cat: 'Kultur', q: 'Wer malte „Die Sternennacht“?', o: ['Vincent van Gogh', 'Claude Monet', 'Paul Cézanne', 'Edvard Munch'] },
  { id: 'kul05', cat: 'Kultur', q: 'In welcher Stadt steht der Louvre?', o: ['Paris', 'Madrid', 'Rom', 'Brüssel'] },
  { id: 'kul06', cat: 'Kultur', q: 'Wer schrieb „Der kleine Prinz“?', o: ['Antoine de Saint-Exupéry', 'Albert Camus', 'Jules Verne', 'Michael Ende'] },
  { id: 'kul07', cat: 'Kultur', q: 'Wer schrieb die Harry-Potter-Romane?', o: ['J. K. Rowling', 'Philip Pullman', 'Suzanne Collins', 'Cornelia Funke'] },
  { id: 'kul08', cat: 'Kultur', q: 'Wer schuf die Skulptur „David“ in Florenz?', o: ['Michelangelo', 'Donatello', 'Bernini', 'Cellini'] },
  { id: 'kul09', cat: 'Kultur', q: 'Wer malte „Der Schrei“?', o: ['Edvard Munch', 'Salvador Dalí', 'Pablo Picasso', 'Wassily Kandinsky'] },
  { id: 'kul10', cat: 'Kultur', q: 'Welcher Maler schnitt sich ein Ohrläppchen ab?', o: ['Vincent van Gogh', 'Paul Gauguin', 'Henri Matisse', 'Édouard Manet'] },
  { id: 'kul11', cat: 'Kultur', q: 'Wer schrieb „Krieg und Frieden“?', o: ['Leo Tolstoi', 'Fjodor Dostojewski', 'Anton Tschechow', 'Iwan Turgenjew'] },
  { id: 'kul12', cat: 'Kultur', q: 'Wer schrieb „Die Verwandlung“, in der ein Mann als Käfer erwacht?', o: ['Franz Kafka', 'Thomas Mann', 'Hermann Hesse', 'Robert Musil'] },
  { id: 'kul13', cat: 'Kultur', q: 'Welche Kunstrichtung begründete Pablo Picasso mit?', o: ['Kubismus', 'Impressionismus', 'Surrealismus', 'Expressionismus'] },
  { id: 'kul14', cat: 'Kultur', q: 'Wer schrieb „1984“?', o: ['George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'H. G. Wells'] },
  { id: 'kul15', cat: 'Kultur', q: 'Welches Museum beherbergt die Sixtinische Kapelle?', o: ['Die Vatikanischen Museen', 'Die Uffizien', 'Der Prado', 'Die Eremitage'] },
  { id: 'kul16', cat: 'Kultur', q: 'Wer schrieb „Stolz und Vorurteil“?', o: ['Jane Austen', 'Charlotte Brontë', 'Virginia Woolf', 'Mary Shelley'] },
  { id: 'kul17', cat: 'Kultur', q: 'Welcher Künstler malte schmelzende Uhren?', o: ['Salvador Dalí', 'René Magritte', 'Joan Miró', 'Max Ernst'] },
  { id: 'kul18', cat: 'Kultur', q: 'Wer schrieb „Der Herr der Ringe“?', o: ['J. R. R. Tolkien', 'C. S. Lewis', 'George R. R. Martin', 'Terry Pratchett'] },
  { id: 'kul19', cat: 'Kultur', q: 'Welche Farbe fehlt im Regenbogen?', o: ['Braun', 'Indigo', 'Violett', 'Orange'] },
  { id: 'kul20', cat: 'Kultur', q: 'Wer schrieb „Die unendliche Geschichte“?', o: ['Michael Ende', 'Otfried Preußler', 'Erich Kästner', 'James Krüss'] },
  { id: 'kul21', cat: 'Kultur', q: 'Welche mexikanische Malerin ist für ihre Selbstporträts berühmt?', o: ['Frida Kahlo', 'Remedios Varo', 'Leonora Carrington', 'Tamara de Lempicka'] },
  { id: 'kul22', cat: 'Kultur', q: 'Wer schrieb „Die Blechtrommel“?', o: ['Günter Grass', 'Heinrich Böll', 'Siegfried Lenz', 'Martin Walser'] },

  // ── Musik ───────────────────────────────────────────────────────────────
  { id: 'mus01', cat: 'Musik', q: 'Welche Band veröffentlichte „Bohemian Rhapsody“?', o: ['Queen', 'The Beatles', 'Led Zeppelin', 'Pink Floyd'] },
  { id: 'mus02', cat: 'Musik', q: 'Wer komponierte „Eine kleine Nachtmusik“?', o: ['Mozart', 'Beethoven', 'Haydn', 'Bach'] },
  { id: 'mus03', cat: 'Musik', q: 'In welcher Mozart-Oper singt die Königin der Nacht?', o: ['Die Zauberflöte', 'Don Giovanni', 'Figaros Hochzeit', 'Così fan tutte'] },
  { id: 'mus04', cat: 'Musik', q: 'Welches Instrument hat 88 Tasten?', o: ['Klavier', 'Orgel', 'Akkordeon', 'Cembalo'] },
  { id: 'mus05', cat: 'Musik', q: 'Wer wird „King of Pop“ genannt?', o: ['Michael Jackson', 'Prince', 'Elvis Presley', 'James Brown'] },
  { id: 'mus06', cat: 'Musik', q: 'Aus welcher Stadt stammen die Beatles?', o: ['Liverpool', 'London', 'Manchester', 'Birmingham'] },
  { id: 'mus07', cat: 'Musik', q: 'Welcher Komponist war am Ende seines Lebens taub?', o: ['Ludwig van Beethoven', 'Franz Liszt', 'Frédéric Chopin', 'Robert Schumann'] },
  { id: 'mus08', cat: 'Musik', q: 'Wie viele Saiten hat eine klassische Gitarre?', o: ['6', '4', '7', '12'] },
  { id: 'mus09', cat: 'Musik', q: 'Welche Sängerin sang „Rolling in the Deep“?', o: ['Adele', 'Amy Winehouse', 'Duffy', 'Florence Welch'] },
  { id: 'mus10', cat: 'Musik', q: 'Welcher Tanz wird im Dreivierteltakt getanzt?', o: ['Walzer', 'Tango', 'Foxtrott', 'Cha-Cha-Cha'] },
  { id: 'mus11', cat: 'Musik', q: 'Wer schrieb „Die vier Jahreszeiten“?', o: ['Antonio Vivaldi', 'Johann Sebastian Bach', 'Georg Friedrich Händel', 'Arcangelo Corelli'] },
  { id: 'mus12', cat: 'Musik', q: 'Welches Instrument spielte Louis Armstrong?', o: ['Trompete', 'Saxofon', 'Posaune', 'Klarinette'] },
  { id: 'mus13', cat: 'Musik', q: 'Wie heißt der Wettbewerb, bei dem europäische Länder gegeneinander singen?', o: ['Eurovision Song Contest', 'Europa-Festival', 'Song of Europe', 'Continental Song Cup'] },
  { id: 'mus14', cat: 'Musik', q: 'Welche Band sang „Stairway to Heaven“?', o: ['Led Zeppelin', 'Deep Purple', 'The Who', 'Black Sabbath'] },
  { id: 'mus15', cat: 'Musik', q: 'Wie viele Töne hat eine Oktave in der Dur-Tonleiter (ohne Wiederholung des Grundtons)?', o: ['7', '8', '5', '12'] },
  { id: 'mus16', cat: 'Musik', q: 'Wer sang „Like a Prayer“?', o: ['Madonna', 'Cher', 'Whitney Houston', 'Cyndi Lauper'] },
  { id: 'mus17', cat: 'Musik', q: 'Welches Instrument bedient man mit Pedalen, Manualen und Registern?', o: ['Die Orgel', 'Das Cembalo', 'Das Harmonium', 'Das Klavichord'] },
  { id: 'mus18', cat: 'Musik', q: 'Aus welchem Land stammt der Fado?', o: ['Portugal', 'Spanien', 'Italien', 'Griechenland'] },

  // ── Film & Fernsehen ────────────────────────────────────────────────────
  { id: 'fil01', cat: 'Film', q: 'Aus welchem Film stammt „Ich mache ihm ein Angebot, das er nicht ablehnen kann“?', o: ['Der Pate', 'Scarface', 'Goodfellas', 'Casino'] },
  { id: 'fil02', cat: 'Film', q: 'Wer führte Regie bei „Pulp Fiction“?', o: ['Quentin Tarantino', 'Martin Scorsese', 'Guy Ritchie', 'Die Coen-Brüder'] },
  { id: 'fil03', cat: 'Film', q: 'Welcher Film spielt auf dem Planeten Pandora?', o: ['Avatar', 'Interstellar', 'Dune', 'Star Trek'] },
  { id: 'fil04', cat: 'Film', q: 'Wie heißt der Zauberschüler mit der Blitznarbe?', o: ['Harry Potter', 'Ron Weasley', 'Neville Longbottom', 'Draco Malfoy'] },
  { id: 'fil05', cat: 'Film', q: 'Welcher Schauspieler spielte James Bond zuerst im Kino?', o: ['Sean Connery', 'Roger Moore', 'George Lazenby', 'Timothy Dalton'] },
  { id: 'fil06', cat: 'Film', q: 'In welchem Film hört man „Möge die Macht mit dir sein“?', o: ['Star Wars', 'Star Trek', 'Dune', 'Matrix'] },
  { id: 'fil07', cat: 'Film', q: 'Welche Serie spielt in Westeros?', o: ['Game of Thrones', 'The Witcher', 'Vikings', 'The Last Kingdom'] },
  { id: 'fil08', cat: 'Film', q: 'Wer spielte Jack in „Titanic“?', o: ['Leonardo DiCaprio', 'Brad Pitt', 'Matt Damon', 'Johnny Depp'] },
  { id: 'fil09', cat: 'Film', q: 'Welches Studio produzierte „Findet Nemo“?', o: ['Pixar', 'DreamWorks', 'Illumination', 'Studio Ghibli'] },
  { id: 'fil10', cat: 'Film', q: 'Welche Farbe hat die Pille, die Neo in „Matrix“ nimmt?', o: ['Rot', 'Blau', 'Grün', 'Weiß'] },
  { id: 'fil11', cat: 'Film', q: 'Wie heißt der Preis der amerikanischen Filmakademie?', o: ['Oscar', 'Golden Globe', 'Bafta', 'Palme d’Or'] },
  { id: 'fil12', cat: 'Film', q: 'Welcher Regisseur drehte „Schindlers Liste“?', o: ['Steven Spielberg', 'Ridley Scott', 'Roman Polański', 'Oliver Stone'] },
  { id: 'fil13', cat: 'Film', q: 'In welcher Stadt spielt die Serie „Friends“?', o: ['New York', 'Chicago', 'Los Angeles', 'Boston'] },
  { id: 'fil14', cat: 'Film', q: 'Wie heißt das japanische Animationsstudio hinter „Chihiros Reise“?', o: ['Studio Ghibli', 'Toei Animation', 'Madhouse', 'Kyoto Animation'] },
  { id: 'fil15', cat: 'Film', q: 'Welcher Film gewann als erster Animationsfilm eine Oscar-Nominierung als bester Film?', o: ['Die Schöne und das Biest', 'Der König der Löwen', 'Toy Story', 'Aladdin'] },
  { id: 'fil16', cat: 'Film', q: 'Wie heißt der Chemielehrer in „Breaking Bad“?', o: ['Walter White', 'Jesse Pinkman', 'Saul Goodman', 'Hank Schrader'] },
  { id: 'fil17', cat: 'Film', q: 'In welchem Land spielt „Squid Game“?', o: ['Südkorea', 'Japan', 'China', 'Taiwan'] },
  { id: 'fil18', cat: 'Film', q: 'Welcher Schauspieler spielt Iron Man im Marvel-Universum?', o: ['Robert Downey Jr.', 'Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo'] },

  // ── Sport ───────────────────────────────────────────────────────────────
  { id: 'spo01', cat: 'Sport', q: 'Wie viele Spieler einer Fußballmannschaft stehen auf dem Feld?', o: ['11', '10', '12', '9'] },
  { id: 'spo02', cat: 'Sport', q: 'Alle wie viele Jahre finden die Olympischen Sommerspiele statt?', o: ['4', '2', '3', '5'] },
  { id: 'spo03', cat: 'Sport', q: 'Wie viele Ringe hat das olympische Symbol?', o: ['5', '4', '6', '7'] },
  { id: 'spo04', cat: 'Sport', q: 'Welche Sportart wird in Wimbledon gespielt?', o: ['Tennis', 'Cricket', 'Golf', 'Polo'] },
  { id: 'spo05', cat: 'Sport', q: 'Wie lang ist ein Marathon?', o: ['42,195 km', '40 km', '45 km', '38,5 km'] },
  { id: 'spo06', cat: 'Sport', q: 'Wie viele Punkte bringt ein Touchdown im American Football?', o: ['6', '7', '3', '5'] },
  { id: 'spo07', cat: 'Sport', q: 'Wie viele Löcher hat eine volle Golfrunde?', o: ['18', '12', '16', '20'] },
  { id: 'spo08', cat: 'Sport', q: 'In welchem Land entstand der moderne Fußball?', o: ['England', 'Italien', 'Brasilien', 'Deutschland'] },
  { id: 'spo09', cat: 'Sport', q: 'Wie viele Spieler hat eine Basketballmannschaft auf dem Feld?', o: ['5', '6', '7', '4'] },
  { id: 'spo10', cat: 'Sport', q: 'Welches Land hat die meisten Fußball-Weltmeistertitel?', o: ['Brasilien', 'Deutschland', 'Italien', 'Argentinien'] },
  { id: 'spo11', cat: 'Sport', q: 'Wie heißt das wichtigste Radrennen der Welt?', o: ['Tour de France', 'Giro d’Italia', 'Vuelta a España', 'Paris–Roubaix'] },
  { id: 'spo12', cat: 'Sport', q: 'Wie viele Runden hat ein Boxkampf um einen WM-Titel maximal?', o: ['12', '10', '15', '8'] },
  { id: 'spo13', cat: 'Sport', q: 'Welche Sportart betreibt man auf einem „Half Pipe“?', o: ['Snowboarden', 'Klettern', 'Rudern', 'Turnen'] },
  { id: 'spo14', cat: 'Sport', q: 'Wie heißt der Punktestand „null“ beim Tennis?', o: ['Love', 'Zero', 'Nil', 'Duck'] },
  { id: 'spo15', cat: 'Sport', q: 'Aus wie vielen Disziplinen besteht ein Triathlon?', o: ['3', '2', '4', '5'] },
  { id: 'spo16', cat: 'Sport', q: 'In welcher Sportart gibt es den „Slam Dunk“?', o: ['Basketball', 'Volleyball', 'Handball', 'Baseball'] },
  { id: 'spo17', cat: 'Sport', q: 'Welches Land richtete die Olympischen Sommerspiele 2021 aus?', o: ['Japan', 'China', 'Brasilien', 'Frankreich'] },
  { id: 'spo18', cat: 'Sport', q: 'Wie viele Felder hat ein Schachbrett?', o: ['64', '81', '49', '100'] },

  // ── Essen & Trinken ─────────────────────────────────────────────────────
  { id: 'ess01', cat: 'Essen', q: 'Aus welchem Land stammt Sushi?', o: ['Japan', 'China', 'Korea', 'Thailand'] },
  { id: 'ess02', cat: 'Essen', q: 'Welches Gewürz ist das teuerste der Welt?', o: ['Safran', 'Vanille', 'Kardamom', 'Zimt'] },
  { id: 'ess03', cat: 'Essen', q: 'Woraus wird Guacamole hauptsächlich gemacht?', o: ['Avocado', 'Erbsen', 'Zucchini', 'Spinat'] },
  { id: 'ess04', cat: 'Essen', q: 'Aus welchem Land kommt der Käse Feta?', o: ['Griechenland', 'Italien', 'Türkei', 'Bulgarien'] },
  { id: 'ess05', cat: 'Essen', q: 'Woraus besteht Hummus hauptsächlich?', o: ['Kichererbsen', 'Linsen', 'Bohnen', 'Sesam'] },
  { id: 'ess06', cat: 'Essen', q: 'Aus welcher Pflanze wird Tequila gemacht?', o: ['Agave', 'Zuckerrohr', 'Kaktusfeige', 'Mais'] },
  { id: 'ess07', cat: 'Essen', q: 'Welches Land trinkt pro Kopf am meisten Kaffee?', o: ['Finnland', 'Italien', 'Brasilien', 'Österreich'] },
  { id: 'ess08', cat: 'Essen', q: 'Wie heißt der scharfe grüne japanische Meerrettich?', o: ['Wasabi', 'Miso', 'Yuzu', 'Ponzu'] },
  { id: 'ess09', cat: 'Essen', q: 'Welche Nudelsorte ist ein flaches, breites Band?', o: ['Tagliatelle', 'Penne', 'Fusilli', 'Rigatoni'] },
  { id: 'ess10', cat: 'Essen', q: 'Aus welchem Land stammt die Paella?', o: ['Spanien', 'Portugal', 'Italien', 'Mexiko'] },
  { id: 'ess11', cat: 'Essen', q: 'Welche Zutat macht Risotto cremig?', o: ['Stärke aus dem Rundkornreis', 'Sahne', 'Mehl', 'Ei'] },
  { id: 'ess12', cat: 'Essen', q: 'Was ist Sake?', o: ['Reiswein', 'Reisessig', 'Pflaumenschnaps', 'Grüner Tee'] },
  { id: 'ess13', cat: 'Essen', q: 'Wie heißt die italienische Nachspeise aus Mascarpone und Espresso?', o: ['Tiramisu', 'Panna Cotta', 'Zabaione', 'Cannoli'] },
  { id: 'ess14', cat: 'Essen', q: 'Aus welchem Land kommt Kimchi?', o: ['Korea', 'Japan', 'China', 'Vietnam'] },
  { id: 'ess15', cat: 'Essen', q: 'Welche Frucht ist botanisch gesehen eine Beere?', o: ['Die Banane', 'Die Erdbeere', 'Die Himbeere', 'Die Brombeere'] },
  { id: 'ess16', cat: 'Essen', q: 'Welcher Wein wird aus der Rebsorte Grüner Veltliner gemacht?', o: ['Weißwein', 'Rotwein', 'Roséwein', 'Dessertwein'] },
  { id: 'ess17', cat: 'Essen', q: 'Was ist Ceviche?', o: ['In Zitrussaft marinierter roher Fisch', 'Eine Fischsuppe', 'Gegrillte Meeresfrüchte', 'Ein Reisgericht'] },
  { id: 'ess18', cat: 'Essen', q: 'Welches Getreide steckt in klassischem Bier?', o: ['Gerste', 'Hafer', 'Roggen', 'Hirse'] },
  { id: 'ess19', cat: 'Essen', q: 'Wie heißt die scharfe nordafrikanische Gewürzpaste?', o: ['Harissa', 'Sambal', 'Sriracha', 'Chimichurri'] },
  { id: 'ess20', cat: 'Essen', q: 'Welches Land ist der größte Olivenölproduzent?', o: ['Spanien', 'Italien', 'Griechenland', 'Türkei'] },

  // ── Sprache, Zahlen & Alltag ────────────────────────────────────────────
  { id: 'all01', cat: 'Alltag', q: 'Wie viele Minuten hat ein Tag?', o: ['1440', '1200', '1600', '2400'] },
  { id: 'all02', cat: 'Alltag', q: 'Wie viel ist die Quadratwurzel aus 144?', o: ['12', '14', '16', '11'] },
  { id: 'all03', cat: 'Alltag', q: 'Welche Sprache hat weltweit die meisten Muttersprachler?', o: ['Mandarin-Chinesisch', 'Englisch', 'Spanisch', 'Hindi'] },
  { id: 'all04', cat: 'Alltag', q: 'Welche Farbe ergibt Blau gemischt mit Gelb?', o: ['Grün', 'Lila', 'Braun', 'Orange'] },
  { id: 'all05', cat: 'Alltag', q: 'Wie viele Sekunden hat eine Stunde?', o: ['3600', '360', '6000', '1800'] },
  { id: 'all06', cat: 'Alltag', q: 'Wie viele Buchstaben hat das deutsche Grundalphabet ohne Umlaute und ß?', o: ['26', '24', '28', '30'] },
  { id: 'all07', cat: 'Alltag', q: 'Was bedeutet die Abkürzung „etc.“?', o: ['et cetera – und so weiter', 'et cera – und ähnlich', 'estimated – geschätzt', 'et casus – im Fall'] },
  { id: 'all08', cat: 'Alltag', q: 'Wie viele Nullen hat eine Milliarde?', o: ['9', '6', '12', '8'] },
  { id: 'all09', cat: 'Alltag', q: 'Welche Sprache ist Amtssprache in Brasilien?', o: ['Portugiesisch', 'Spanisch', 'Brasilianisch', 'Französisch'] },
  { id: 'all10', cat: 'Alltag', q: 'Was bedeutet „Carpe diem“?', o: ['Nutze den Tag', 'Lebe wohl', 'So ist das Leben', 'Vertraue der Zeit'] },
  { id: 'all11', cat: 'Alltag', q: 'Wie viele Grad hat ein Kreis?', o: ['360', '180', '270', '400'] },
  { id: 'all12', cat: 'Alltag', q: 'Was ist ein „Palindrom“?', o: ['Ein Wort, das rückwärts gleich lautet', 'Ein Wort mit doppelter Bedeutung', 'Ein Wort ohne Vokale', 'Ein zusammengesetztes Wort'] },
  { id: 'all13', cat: 'Alltag', q: 'Welche römische Zahl steht für 50?', o: ['L', 'C', 'D', 'X'] },
  { id: 'all14', cat: 'Alltag', q: 'Wie viele Karten hat ein Skatblatt?', o: ['32', '52', '36', '24'] },
  { id: 'all15', cat: 'Alltag', q: 'Welches Sternzeichen hat der 1. Januar?', o: ['Steinbock', 'Wassermann', 'Schütze', 'Fische'] },
  { id: 'all16', cat: 'Alltag', q: 'Was misst man in Karat bei Diamanten?', o: ['Das Gewicht', 'Die Reinheit', 'Den Schliff', 'Die Farbe'] },
  { id: 'all17', cat: 'Alltag', q: 'Wie heißt die Währung Japans?', o: ['Yen', 'Won', 'Yuan', 'Baht'] },
  { id: 'all18', cat: 'Alltag', q: 'Wie viele Felder hat ein Sudoku-Gitter?', o: ['81', '64', '100', '72'] },
  { id: 'all19', cat: 'Alltag', q: 'Welches Verkehrszeichen ist achteckig?', o: ['Das Stoppschild', 'Die Vorfahrtstraße', 'Das Halteverbot', 'Die Einbahnstraße'] },
  { id: 'all20', cat: 'Alltag', q: 'Welche Blutgruppe ist in Europa am häufigsten?', o: ['A positiv', '0 negativ', 'AB positiv', 'B negativ'] },

  // ── Mythologie & Religion ───────────────────────────────────────────────
  { id: 'myt01', cat: 'Mythos', q: 'Wer ist in der griechischen Mythologie der Göttervater?', o: ['Zeus', 'Poseidon', 'Hades', 'Apollon'] },
  { id: 'myt02', cat: 'Mythos', q: 'Welcher nordische Gott führt den Hammer Mjölnir?', o: ['Thor', 'Odin', 'Loki', 'Baldur'] },
  { id: 'myt03', cat: 'Mythos', q: 'Wie heißt das geflügelte Pferd der griechischen Sage?', o: ['Pegasos', 'Zentaur', 'Chimära', 'Greif'] },
  { id: 'myt04', cat: 'Mythos', q: 'Welche Stadt eroberten die Griechen mit einem hölzernen Pferd?', o: ['Troja', 'Sparta', 'Theben', 'Korinth'] },
  { id: 'myt05', cat: 'Mythos', q: 'Wer musste zwölf Aufgaben bewältigen?', o: ['Herakles', 'Odysseus', 'Achilles', 'Perseus'] },
  { id: 'myt06', cat: 'Mythos', q: 'Wie heißt das heilige Buch des Islam?', o: ['Der Koran', 'Die Tora', 'Die Veden', 'Das Avesta'] },
  { id: 'myt07', cat: 'Mythos', q: 'Wie viele Gebote stehen auf den Tafeln des Mose?', o: ['10', '7', '12', '5'] },
  { id: 'myt08', cat: 'Mythos', q: 'Wo liegt der Sitz des Papstes?', o: ['Vatikanstadt', 'Rom-Trastevere', 'Assisi', 'Florenz'] },
  { id: 'myt09', cat: 'Mythos', q: 'Welcher Fluss gilt im Hinduismus als heilig?', o: ['Der Ganges', 'Der Indus', 'Der Brahmaputra', 'Der Jamuna'] },
  { id: 'myt10', cat: 'Mythos', q: 'Welches Tier symbolisiert in Ägypten die Göttin Bastet?', o: ['Die Katze', 'Der Falke', 'Das Krokodil', 'Der Skarabäus'] },
  { id: 'myt11', cat: 'Mythos', q: 'Wie heißt das Fest, an dem Juden den Auszug aus Ägypten feiern?', o: ['Pessach', 'Chanukka', 'Jom Kippur', 'Sukkot'] },
  { id: 'myt12', cat: 'Mythos', q: 'Wer war in der römischen Mythologie die Göttin der Liebe?', o: ['Venus', 'Juno', 'Minerva', 'Diana'] },
  { id: 'myt13', cat: 'Mythos', q: 'Welche Kreatur wird als halb Mensch, halb Stier beschrieben?', o: ['Der Minotaurus', 'Der Zentaur', 'Der Satyr', 'Der Faun'] },
  { id: 'myt14', cat: 'Mythos', q: 'Wie heißt der Weltuntergang in der nordischen Mythologie?', o: ['Ragnarök', 'Walhall', 'Yggdrasil', 'Midgard'] },
];
